import type { Metadata } from 'next'
import Link from 'next/link'
import { ChevronRight } from 'lucide-react'
import Header from '@/components/layout/Header'
import Footer from '@/components/layout/Footer'
import PersonalFinanceToolPage from '@/components/layout/PersonalFinanceToolPage'
import InflationGuard from '@/components/tools/personal-finance/InflationGuard'
export const metadata: Metadata = { title: 'Inflation Guard — Proyeksi Daya Beli vs Inflasi | FincTools', description: 'Proyeksikan penurunan daya beli uang akibat inflasi dan hitung berapa nilai riil uang kamu di masa depan.' }
export default function Page() {
  return (<><Header /><main className="mx-auto max-w-4xl px-4 py-8">
    <nav className="flex items-center gap-1 text-xs text-[--text-secondary] mb-6"><Link href="/" className="hover:text-finc-green">Home</Link><ChevronRight size={12}/><Link href="/personal-finance" className="hover:text-finc-green">Personal Finance</Link><ChevronRight size={12}/><span className="text-[--text-primary] font-medium">Inflation Guard</span></nav>
    <PersonalFinanceToolPage name="Inflation Guard" subcategory="Perencanaan Inflasi"
      description="Inflation Guard memvisualisasikan dampak inflasi terhadap daya beli uang kamu dari waktu ke waktu. Uang yang disimpan tanpa return investasi akan terus berkurang nilainya secara riil akibat inflasi."
      steps={[{title:'Isi Jumlah Uang Saat Ini',desc:'Masukkan nominal uang atau aset yang ingin kamu proyeksikan daya belinya di masa depan.'},{title:'Set Tingkat Inflasi',desc:'Inflasi Indonesia rata-rata historis 3–5% per tahun. Gunakan asumsi konservatif 5% untuk perencanaan yang lebih aman.'},{title:'Set Periode',desc:'Berapa tahun ke depan yang ingin kamu proyeksikan — bisa untuk perencanaan pensiun, pendidikan anak, atau tujuan jangka panjang.'},{title:'Baca Hasilnya',desc:'Daya beli riil uang tersebut di masa depan, nilai nominalnya, dan berapa persen daya belinya yang hilang.'}]}
      formula={"Nilai Nominal = Jumlah × (1 + Inflasi%)^Tahun\nDaya Beli Riil = Jumlah / (1 + Inflasi%)^Tahun\nKehilangan Daya Beli = Jumlah - Daya Beli Riil\n% Penurunan = (Kehilangan / Jumlah) × 100"}
      formulaExample={"Rp 100.000.000 | Inflasi 4% | 10 tahun\nNilai Nominal = Rp 148.000.000 (dibutuhkan untuk setara)\nDaya Beli Riil = Rp 67.600.000 (nilai riil uang saat ini)\nKehilangan Daya Beli = Rp 32.400.000 (-32.4%)"}
      variables={[{name:'Nilai Nominal',desc:'Berapa uang yang dibutuhkan di masa depan untuk membeli barang yang sama seperti saat ini'},{name:'Daya Beli Riil',desc:'Nilai riil uang kamu di masa depan setelah disesuaikan inflasi — dalam nilai uang saat ini'},{name:'Faktor Inflasi',desc:'Pengali inflasi kumulatif selama periode yang dipilih'}]}
      history={"Konsep purchasing power (daya beli) dan dampak inflasi terhadap nilai uang telah dipelajari sejak abad ke-18 oleh ekonom klasik seperti David Hume dan John Locke. Irving Fisher, ekonom Amerika awal abad ke-20, adalah yang pertama merumuskan hubungan matematis antara suku bunga nominal, suku bunga riil, dan inflasi dalam persamaan yang dikenal sebagai Fisher Equation.\n\nDi Indonesia, inflasi pernah mencapai ribuan persen saat krisis 1997–1998. Bank Indonesia menetapkan target inflasi 2–4% per tahun sejak era reformasi, namun secara historis inflasi aktual berada di kisaran 3–7% per tahun.\n\nPemahaman inflasi sangat penting untuk perencanaan pensiun — karena apa yang cukup untuk hidup hari ini mungkin tidak cukup dalam 20–30 tahun mendatang jika tidak diiringi investasi yang mengalahkan inflasi."}
      faqs={[{q:'Mengapa uang yang disimpan di bawah kasur berbahaya?',a:'Uang tunai yang tidak diinvestasikan kehilangan daya beli setiap tahun seiring inflasi. Rp 100 juta hari ini dengan inflasi 4% akan setara Rp 67 juta dalam 10 tahun — artinya kehilangan Rp 33 juta daya beli tanpa disadari.'},{q:'Instrumen investasi mana yang bisa mengalahkan inflasi?',a:'Reksa dana saham secara historis memberikan return 12–18%/tahun — jauh di atas inflasi. Emas secara historis juga mengalahkan inflasi jangka panjang. Deposito dan tabungan biasa sering tidak bisa mengalahkan inflasi.'},{q:'Bagaimana inflasi mempengaruhi FIRE Number?',a:'FIRE Number harus mempertimbangkan inflasi. Pengeluaran Rp 10 juta/bulan hari ini akan setara Rp 14.8 juta dalam 10 tahun dengan inflasi 4%. Pastikan FIRE Number dihitung dengan proyeksi pengeluaran yang sudah disesuaikan inflasi.'},{q:'Apakah target inflasi Bank Indonesia bisa dijadikan patokan?',a:'Target BI adalah 2–4% per tahun, namun aktualnya bisa lebih tinggi terutama saat global shock. Untuk perencanaan konservatif, gunakan 5% sebagai asumsi inflasi.'}]}
      related={[{name:'Wealth Freedom Planner',href:'/personal-finance/wealth-freedom-planner',desc:'Hitung FIRE Number yang sudah memperhitungkan dampak inflasi'},{name:'Gold vs Inflation Analyzer',href:'/investasi/gold-vs-inflation-analyzer',desc:'Bandingkan return emas versus inflasi secara spesifik'},{name:'DCA Simulator',href:'/investasi/dca-simulator',desc:'Simulasikan investasi yang mengalahkan inflasi'},{name:'Savings Growth Simulator',href:'/personal-finance/savings-growth-simulator',desc:'Lihat apakah return tabunganmu mengalahkan inflasi'}]}
      references={['Fisher, I. (1911). <em>The Purchasing Power of Money.</em> Macmillan.','BI. <em>Laporan Perekonomian Indonesia.</em> <a href="https://bi.go.id" target="_blank" rel="noopener noreferrer" class="text-finc-green hover:underline">bi.go.id</a>','BPS. <em>Inflasi Indonesia.</em> <a href="https://bps.go.id" target="_blank" rel="noopener noreferrer" class="text-finc-green hover:underline">bps.go.id</a>']}
    ><InflationGuard /></PersonalFinanceToolPage>
  </main><Footer /></>)
}
