import type { Metadata } from 'next'
import Link from 'next/link'
import { ChevronRight } from 'lucide-react'
import Header from '@/components/layout/Header'
import Footer from '@/components/layout/Footer'
import PersonalFinanceToolPage from '@/components/layout/PersonalFinanceToolPage'
import SavingsGrowthSimulator from '@/components/tools/personal-finance/SavingsGrowthSimulator'
export const metadata: Metadata = { title: 'Savings Growth Simulator — Proyeksi Tabungan Jangka Panjang | FincTools', description: 'Proyeksikan pertumbuhan tabungan dengan bunga majemuk. Lihat dampak dahsyat compound interest selama bertahun-tahun.' }
export default function Page() {
  return (<><Header /><main className="mx-auto max-w-4xl px-4 py-8">
    <nav className="flex items-center gap-1 text-xs text-[--text-secondary] mb-6"><Link href="/" className="hover:text-finc-green">Home</Link><ChevronRight size={12}/><Link href="/personal-finance" className="hover:text-finc-green">Personal Finance</Link><ChevronRight size={12}/><span className="text-[--text-primary] font-medium">Savings Growth Simulator</span></nav>
    <PersonalFinanceToolPage name="Savings Growth Simulator" subcategory="Pertumbuhan Tabungan"
      description="Savings Growth Simulator memproyeksikan pertumbuhan tabungan dan investasi dengan bunga majemuk, menunjukkan betapa dahsyatnya efek compound interest ketika dijalankan konsisten dalam jangka panjang."
      steps={[{title:'Isi Tabungan Awal',desc:'Berapa yang sudah kamu miliki saat ini untuk mulai — bisa nol jika memulai dari awal.'},{title:'Isi Tabungan per Bulan',desc:'Jumlah yang akan rutin ditambahkan setiap bulan — konsistensi lebih penting dari jumlahnya.'},{title:'Set Return/Bunga Tahunan',desc:'Reksa dana pasar uang sekitar 4–6%. Reksa dana campuran 8–12%. Reksa dana saham 12–18% (historis, tidak dijamin).'},{title:'Set Periode',desc:'Semakin panjang periode, semakin dahsyat efek compound interest — bahkan tambahan 5 tahun membuat perbedaan luar biasa.'},{title:'Baca Proyeksinya',desc:'Nilai akhir, total yang disetorkan, dan total bunga yang dihasilkan ditampilkan.'}]}
      formula={"FV = PV × (1+r)^n + PMT × ((1+r)^n - 1) / r\nr = return per bulan (return tahunan / 12)\nn = jumlah bulan\nPV = tabungan awal\nPMT = tabungan per bulan"}
      formulaExample={"Tabungan awal Rp 10jt + Rp 1jt/bln selama 5 tahun @ 8%/tahun\nr = 8%/12 = 0.667%/bln | n = 60 bln\nFV = 10jt×(1.0067)^60 + 1jt×((1.0067)^60-1)/0.0067\nFV ≈ Rp 90.100.000 (setor Rp 70jt, bunga Rp 20jt)"}
      variables={[{name:'PV (Present Value)',desc:'Tabungan awal yang sudah dimiliki saat ini'},{name:'PMT (Payment)',desc:'Jumlah tabungan tetap yang ditambahkan setiap bulan'},{name:'r',desc:'Return per bulan = return tahunan dibagi 12'},{name:'n',desc:'Jumlah bulan total periode investasi'},{name:'FV (Future Value)',desc:'Nilai akhir portofolio setelah semua setoran dan bunga majemuk'}]}
      history={"Compound interest — bunga berbunga — adalah salah satu konsep paling powerful dalam keuangan. Albert Einstein dikutip menyebutnya sebagai 'keajaiban dunia kedelapan' meski kutipan ini kemungkinan apokrifal.\n\nSecara historis, matematiawan Jacob Bernoulli menemukan konstanta e (Euler's number) pada 1683 saat mempelajari pertumbuhan bunga majemuk secara kontinu. Formula ini kemudian menjadi dasar seluruh teori keuangan modern.\n\nBenjamin Franklin meninggalkan warisan Rp 5.000 pound sterling (sekitar $4.000) untuk kota Boston dan Philadelphia saat wafat pada 1790 — dengan syarat tidak boleh diambil selama 100 tahun. Setelah 100 tahun, nilai warisan itu tumbuh menjadi ~$500.000 hanya karena compound interest. Ini adalah demonstrasi nyata kekuatan waktu dan bunga majemuk."}
      faqs={[{q:'Apakah lebih baik menabung banyak dulu atau mulai dari kecil tapi sekarang?',a:'Mulai sekarang dengan jumlah kecil jauh lebih baik daripada menunggu bisa menabung besar. Satu bulan keterlambatan adalah satu bulan bunga majemuk yang hilang selamanya. Mulai dengan Rp 100.000/bulan hari ini lebih baik dari Rp 1.000.000/bulan setahun kemudian.'},{q:'Perbedaan besar antara return 8% dan 12% itu seberapa signifikan?',a:'Sangat signifikan dalam jangka panjang. Rp 1.000.000/bulan selama 30 tahun: dengan return 8% menghasilkan ~Rp 1.5 miliar, dengan return 12% menghasilkan ~Rp 3.5 miliar. Perbedaan return 4% menghasilkan selisih Rp 2 miliar.'},{q:'Apakah reksa dana pasar uang aman untuk tabungan?',a:'Reksa dana pasar uang berinvestasi di instrumen pasar uang yang sangat konservatif dan likuid. Risikonya sangat rendah namun tidak nol. Untuk tujuan jangka pendek (<2 tahun) dan dana darurat, reksa dana pasar uang adalah pilihan yang sangat layak dengan return lebih baik dari deposito.'},{q:'Bagaimana pajak memengaruhi return tabungan?',a:'Deposito dan obligasi dikenakan pajak 10–20% atas bunga/kupon. Reksa dana (di Indonesia) saat ini belum dikenakan pajak atas keuntungan investasi untuk investor ritel, menjadikannya lebih efisien dari segi pajak.'}]}
      related={[{name:'DCA Simulator',href:'/investasi/dca-simulator',desc:'Simulasi khusus untuk investasi di reksa dana dan saham'},{name:'Goal Achiever Planner',href:'/personal-finance/goal-achiever-planner',desc:'Hitung tabungan yang dibutuhkan untuk mencapai tujuan tertentu'},{name:'Wealth Freedom Planner',href:'/personal-finance/wealth-freedom-planner',desc:'Proyeksikan kapan tabungan ini mencapai FIRE Number'},{name:'Inflation Guard',href:'/personal-finance/inflation-guard',desc:'Pastikan return tabunganmu mengalahkan inflasi'}]}
      references={['Siegel, J.J. (2014). <em>Stocks for the Long Run.</em> McGraw-Hill.','Malkiel, B.G. (1973). <em>A Random Walk Down Wall Street.</em> Norton.','OJK. <em>Panduan Reksa Dana.</em> <a href="https://ojk.go.id" target="_blank" rel="noopener noreferrer" class="text-finc-green hover:underline">ojk.go.id</a>']}
    ><SavingsGrowthSimulator /></PersonalFinanceToolPage>
  </main><Footer /></>)
}
