import type { Metadata } from 'next'
import Link from 'next/link'
import { ChevronRight } from 'lucide-react'
import Header from '@/components/layout/Header'
import Footer from '@/components/layout/Footer'
import KriptoToolPage from '@/components/layout/KriptoToolPage'
import CryptoRiskManager from '@/components/tools/kripto/CryptoRiskManager'
export const metadata: Metadata = { title: 'Crypto Risk Manager | FincTools', description: 'Hitung jumlah koin yang aman dibeli berdasarkan modal, persentase risiko per trade, dan stop loss.' }
export default function Page() {
  return (<><Header /><main className="mx-auto max-w-4xl px-4 py-8">
    <nav className="flex items-center gap-1 text-xs text-[--text-secondary] mb-6"><Link href="/" className="hover:text-finc-green">Home</Link><ChevronRight size={12}/><Link href="/kripto" className="hover:text-finc-green">Kripto</Link><ChevronRight size={12}/><span className="text-[--text-primary] font-medium">Crypto Risk Manager</span></nav>
    <KriptoToolPage name="Crypto Risk Manager" description="Hitung jumlah koin yang aman dibeli berdasarkan modal, persentase risiko per trade, dan stop loss."
      steps={[{title:'Isi data aset kripto',desc:'Masukkan data posisi atau investasi kripto kamu pada field yang tersedia.'},{title:'Sesuaikan parameter',desc:'Gunakan slider atau input angka untuk mengubah variabel sesuai kondisi aktual.'},{title:'Baca hasilnya',desc:'Semua kalkulasi berjalan real-time di browser kamu.'},{title:'Gunakan sebagai referensi',desc:'Kripto sangat berisiko. Selalu lakukan riset mandiri dan jangan investasi lebih dari yang siap kamu rugikan.'}]}
      formula="Kalkulasi menggunakan formula standar yang digunakan exchange kripto terkemuka."
      variables={[{name:'Input Kripto',desc:'Semua variabel disesuaikan kebutuhan spesifik tool ini'},{name:'Output',desc:'Hasil kalkulasi real-time untuk manajemen posisi kripto'}]}
      history="Position sizing berbasis risiko untuk kripto mengadaptasi konsep yang sama dari trading forex dan saham — dikembangkan Van K. Tharp dan Ed Seykota. Namun kripto memiliki keunikan: volatilitas jauh lebih tinggi, trading 24/7, dan tidak ada circuit breaker.\n\nHerb Greenberg dan komunitas trader kripto mempopulerkan risk management ketat setelah banyak trader kehilangan seluruh modal selama bear market 2018 dan 2022. Kini, trader profesional kripto umumnya tidak mengambil risiko lebih dari 1–2% modal per trade.\n\nExchange kripto seperti Binance dan OKX kini menyediakan kalkulator risk management bawaan — namun sering kali tidak menghitung berdasarkan persentase modal keseluruhan yang benar."
      faqs={[{q:'Berapa persen risiko per trade yang aman untuk kripto?',a:'Untuk kripto yang sangat volatile, risiko 1% per trade sudah agresif. Banyak trader kripto profesional menggunakan 0.5–1% per trade untuk mengantisipasi volatilitas ekstrem. Dengan 1% risiko, dibutuhkan 100 kali loss beruntun untuk kehilangan semua modal.'},{q:'Apakah tool ini bisa digunakan untuk spot trading (bukan futures)?',a:'Ya. Untuk spot trading, masukkan harga entry dan harga stop loss yang kamu inginkan. Hasilnya adalah jumlah koin yang aman dibeli berdasarkan modal dan stop loss tersebut — tanpa leverage.'},{q:'Apakah tool ini berlaku untuk semua exchange kripto?',a:'Formula dasar berlaku universal, namun setiap exchange memiliki parameter sedikit berbeda (terutama maintenance margin dan insurance fund). Gunakan sebagai estimasi dan verifikasi dengan kalkulator bawaan exchange yang kamu gunakan.'},{q:'Apakah trading kripto dengan leverage direkomendasikan untuk pemula?',a:'Sangat tidak direkomendasikan. Leverage memperbesar keuntungan dan kerugian secara proporsional. Mulai dengan spot trading tanpa leverage, pahami pergerakan harga, sebelum mempertimbangkan futures.'}]}
      related={[{name:'Crypto DCA Simulator',href:'/kripto/crypto-dca-simulator',desc:'Strategi lebih aman untuk investasi kripto jangka panjang'},{name:'Crypto Risk Manager',href:'/kripto/crypto-risk-manager',desc:'Hitung position sizing yang aman untuk trading kripto'},{name:'Risk Manager',href:'/trading/risk-manager',desc:'Versi risk manager untuk forex dan instrumen trading lain'},{name:'DCA Simulator',href:'/investasi/dca-simulator',desc:'Simulasi DCA untuk reksa dana dan saham yang lebih konservatif'}]}
      references={['Nakamoto, S. (2008). <em>Bitcoin: A Peer-to-Peer Electronic Cash System.</em>','OJK. <em>Peraturan Aset Kripto.</em> <a href="https://ojk.go.id" target="_blank" rel="noopener noreferrer" class="text-finc-green hover:underline">ojk.go.id</a>','Bappebti. <em>Regulasi Perdagangan Aset Kripto.</em> <a href="https://bappebti.go.id" target="_blank" rel="noopener noreferrer" class="text-finc-green hover:underline">bappebti.go.id</a>']}
    ><CryptoRiskManager /></KriptoToolPage>
  </main><Footer /></>)
}
