import type { Metadata } from 'next'
import Link from 'next/link'
import { ChevronRight } from 'lucide-react'
import Header from '@/components/layout/Header'
import Footer from '@/components/layout/Footer'
import KreditToolPage from '@/components/layout/KreditToolPage'
import RentalYieldAnalyzer from '@/components/tools/kredit/RentalYieldAnalyzer'
export const metadata: Metadata = { title: 'Rental Yield Analyzer | FincTools', description: 'Hitung gross yield, net yield, dan total return investasi properti sewa untuk evaluasi kelayakan investasi.' }
export default function Page() {
  return (<><Header /><main className="mx-auto max-w-4xl px-4 py-8">
    <nav className="flex items-center gap-1 text-xs text-[--text-secondary] mb-6"><Link href="/" className="hover:text-finc-green">Home</Link><ChevronRight size={12}/><Link href="/kredit-properti" className="hover:text-finc-green">Kredit & Properti</Link><ChevronRight size={12}/><span className="text-[--text-primary] font-medium">Rental Yield Analyzer</span></nav>
    <KreditToolPage name="Rental Yield Analyzer" description="Hitung gross yield, net yield, dan total return investasi properti sewa untuk evaluasi kelayakan investasi."
      steps={[{title:'Isi data properti atau pinjaman',desc:'Masukkan semua angka yang dibutuhkan sesuai kondisi aktual kamu.'},{title:'Sesuaikan parameter',desc:'Gunakan slider untuk mengubah variabel dan lihat dampaknya secara real-time.'},{title:'Bandingkan skenario',desc:'Ubah satu variabel sekaligus untuk memahami mana yang paling berpengaruh pada hasil.'},{title:'Gunakan untuk pengambilan keputusan',desc:'Hasil kalkulasi ini adalah salah satu bahan pertimbangan — konsultasikan dengan bank atau agen properti untuk informasi terkini.'}]}
      formula="Formula menggunakan standar keuangan properti Indonesia yang berlaku."
      variables={[{name:'Input Properti',desc:'Semua variabel input disesuaikan dengan tool ini'},{name:'Output Analisis',desc:'Hasil kalkulasi real-time untuk mendukung keputusan properti'}]}
      history={"Pasar properti Indonesia telah berkembang pesat sejak deregulasi sektor perumahan pada 1990-an. Indeks Harga Properti Residensial yang dirilis Bank Indonesia setiap kuartal menunjukkan apresiasi properti rata-rata 5–8% per tahun di kota besar.\n\nProgram KPR pertama di Indonesia diluncurkan BTN pada 1976. Sejak saat itu, kepemilikan rumah melalui KPR menjadi jalur utama masyarakat Indonesia dalam membeli properti — dengan tenor hingga 30 tahun dan down payment minimum 10–20%.\n\nRegulasi OJK dan Bank Indonesia terus mengatur pasar KPR untuk menjaga stabilitas finansial dan mencegah gelembung properti yang pernah menghancurkan pasar negara lain."}
      faqs={[{q:'Bagaimana cara mendapatkan bunga KPR terbaik?',a:'Bandingkan penawaran minimal dari 3–5 bank berbeda. Perhatikan bunga fixed periode pertama, bunga floating setelah itu, biaya provisi, dan biaya administrasi. Bank digital dan fintech lending kadang menawarkan bunga lebih kompetitif.'},{q:'Apakah investasi properti masih menarik di era digital?',a:'Properti tetap menjadi aset yang stabil dengan apresiasi jangka panjang dan cash flow dari sewa. Namun likuiditasnya rendah dibanding saham dan reksa dana. Diversifikasi portofolio antara properti dan aset finansial adalah pendekatan yang bijak.'},{q:'Dokumen apa yang dibutuhkan untuk pengajuan KPR?',a:'KTP, KK, slip gaji/SKP 3 bulan terakhir, rekening koran 3–6 bulan, NPWP, dokumen properti (SHM/SHGB, IMB, PBB). Untuk pengusaha: laporan keuangan dan SIUP/NIB.'},{q:'Apakah kalkulasi ini akurat untuk semua bank?',a:'Tool ini menggunakan formula matematika standar. Setiap bank memiliki kebijakan dan produk yang sedikit berbeda. Gunakan hasil kalkulasi sebagai estimasi awal sebelum konsultasi langsung dengan bank.'}]}
      related={[{name:'KPR Affordability Checker',href:'/kredit-properti/kpr-affordability-checker',desc:'Cek dulu kemampuan cicilan KPR berdasarkan penghasilan'},{name:'Buy vs Rent Analyzer',href:'/kredit-properti/buy-vs-rent-analyzer',desc:'Bandingkan finansial beli vs sewa properti'},{name:'Rental Yield Analyzer',href:'/kredit-properti/rental-yield-analyzer',desc:'Hitung yield jika properti disewakan'},{name:'Net Worth Tracker',href:'/personal-finance/net-worth-tracker',desc:'Pantau dampak properti terhadap kekayaan bersihmu'}]}
      references={['BI. <em>Survei Harga Properti Residensial.</em> <a href="https://bi.go.id" target="_blank" rel="noopener noreferrer" class="text-finc-green hover:underline">bi.go.id</a>','OJK. <em>Panduan Kredit Kepemilikan Rumah.</em> <a href="https://ojk.go.id" target="_blank" rel="noopener noreferrer" class="text-finc-green hover:underline">ojk.go.id</a>']}
    ><RentalYieldAnalyzer /></KreditToolPage>
  </main><Footer /></>)
}
