import type { Metadata } from 'next'
import Link from 'next/link'
import { ChevronRight } from 'lucide-react'
import Header from '@/components/layout/Header'
import Footer from '@/components/layout/Footer'
import KriptoToolPage from '@/components/layout/KriptoToolPage'
import StakingRewardProjector from '@/components/tools/kripto/StakingRewardProjector'
export const metadata: Metadata = { title: 'Staking Reward Projector | FincTools', description: 'Proyeksikan reward staking kripto berdasarkan APY, jumlah koin, dan durasi holding dengan atau tanpa compound.' }
export default function Page() {
  return (<><Header /><main className="mx-auto max-w-4xl px-4 py-8">
    <nav className="flex items-center gap-1 text-xs text-[--text-secondary] mb-6"><Link href="/" className="hover:text-finc-green">Home</Link><ChevronRight size={12}/><Link href="/kripto" className="hover:text-finc-green">Kripto</Link><ChevronRight size={12}/><span className="text-[--text-primary] font-medium">Staking Reward Projector</span></nav>
    <KriptoToolPage name="Staking Reward Projector" description="Proyeksikan reward staking kripto berdasarkan APY, jumlah koin, dan durasi holding dengan atau tanpa compound."
      steps={[{title:'Isi data aset kripto',desc:'Masukkan data posisi atau investasi kripto kamu pada field yang tersedia.'},{title:'Sesuaikan parameter',desc:'Gunakan slider atau input angka untuk mengubah variabel sesuai kondisi aktual.'},{title:'Baca hasilnya',desc:'Semua kalkulasi berjalan real-time di browser kamu.'},{title:'Gunakan sebagai referensi',desc:'Kripto sangat berisiko. Selalu lakukan riset mandiri dan jangan investasi lebih dari yang siap kamu rugikan.'}]}
      formula="Kalkulasi menggunakan formula standar yang digunakan exchange kripto terkemuka."
      variables={[{name:'Input Kripto',desc:'Semua variabel disesuaikan kebutuhan spesifik tool ini'},{name:'Output',desc:'Hasil kalkulasi real-time untuk manajemen posisi kripto'}]}
      history="Staking menjadi populer seiring transisi Ethereum dari Proof of Work ke Proof of Stake pada September 2022 (The Merge). Sejak saat itu, staking ETH memungkinkan validator mendapatkan reward ~4–6% APY.\n\nKonsep staking dalam kripto diadaptasi dari Delegated Proof of Stake yang diperkenalkan oleh Dan Larimer pada 2013. Berbeda dengan mining yang butuh hardware mahal, staking hanya membutuhkan koin yang dikunci sebagai jaminan validasi transaksi.\n\nDi Indonesia, platform seperti Pintu dan Tokocrypto menawarkan fitur staking dengan APY yang bervariasi. Namun perhatikan bahwa APY kripto bisa berubah drastis sesuai kondisi jaringan dan partisipasi validator."
      faqs={[{q:'Apakah staking aman dari risiko kehilangan koin?',a:'Ada dua risiko utama: slashing (koin dipotong jika validator berlaku curang atau tidak stabil) dan risiko harga (nilai koin bisa turun lebih besar dari reward yang didapat). Untuk staking via platform terpusat, ada tambahan risiko platform (exchange bangkrut atau hack).'},{q:'Bagaimana cara memilih koin untuk staking?',a:'Prioritaskan koin dengan fundamental kuat, APY yang realistis (APY sangat tinggi >50% biasanya tidak sustainable), dan proyek dengan track record yang sudah terbukti. Hindari koin baru atau proyek tidak dikenal hanya karena APY-nya menarik.'},{q:'Apakah tool ini berlaku untuk semua exchange kripto?',a:'Formula dasar berlaku universal, namun setiap exchange memiliki parameter sedikit berbeda (terutama maintenance margin dan insurance fund). Gunakan sebagai estimasi dan verifikasi dengan kalkulator bawaan exchange yang kamu gunakan.'},{q:'Apakah trading kripto dengan leverage direkomendasikan untuk pemula?',a:'Sangat tidak direkomendasikan. Leverage memperbesar keuntungan dan kerugian secara proporsional. Mulai dengan spot trading tanpa leverage, pahami pergerakan harga, sebelum mempertimbangkan futures.'}]}
      related={[{name:'Crypto DCA Simulator',href:'/kripto/crypto-dca-simulator',desc:'Strategi lebih aman untuk investasi kripto jangka panjang'},{name:'Crypto Risk Manager',href:'/kripto/crypto-risk-manager',desc:'Hitung position sizing yang aman untuk trading kripto'},{name:'Risk Manager',href:'/trading/risk-manager',desc:'Versi risk manager untuk forex dan instrumen trading lain'},{name:'DCA Simulator',href:'/investasi/dca-simulator',desc:'Simulasi DCA untuk reksa dana dan saham yang lebih konservatif'}]}
      references={['Nakamoto, S. (2008). <em>Bitcoin: A Peer-to-Peer Electronic Cash System.</em>','OJK. <em>Peraturan Aset Kripto.</em> <a href="https://ojk.go.id" target="_blank" rel="noopener noreferrer" class="text-finc-green hover:underline">ojk.go.id</a>','Bappebti. <em>Regulasi Perdagangan Aset Kripto.</em> <a href="https://bappebti.go.id" target="_blank" rel="noopener noreferrer" class="text-finc-green hover:underline">bappebti.go.id</a>']}
    ><StakingRewardProjector /></KriptoToolPage>
  </main><Footer /></>)
}
