import type { Metadata } from 'next'
import Link from 'next/link'
import { ChevronRight } from 'lucide-react'
import Header from '@/components/layout/Header'
import Footer from '@/components/layout/Footer'
import SahamToolPage from '@/components/layout/SahamToolPage'
import AveragingStrategyBuilder from '@/components/tools/saham/AveragingStrategyBuilder'
export const metadata: Metadata = { title: 'Averaging Strategy Builder — Hitung Harga Rata-rata Saham | FincTools', description: 'Kalkulasi harga rata-rata beli saham setelah average down atau average up dari dua posisi berbeda.' }
export default function Page() {
  return (<><Header /><main className="mx-auto max-w-4xl px-4 py-8">
    <nav className="flex items-center gap-1 text-xs text-[--text-secondary] mb-6"><Link href="/" className="hover:text-finc-green">Home</Link><ChevronRight size={12}/><Link href="/saham" className="hover:text-finc-green">Saham</Link><ChevronRight size={12}/><span className="text-[--text-primary] font-medium">Averaging Strategy Builder</span></nav>
    <SahamToolPage name="Averaging Strategy Builder" description="Averaging Strategy Builder menghitung harga rata-rata beli saham setelah melakukan pembelian di dua harga berbeda — baik average down saat harga turun maupun average up saat harga naik."
      steps={[{title:'Isi Harga Beli Pertama',desc:'Masukkan harga per lembar saat kamu pertama kali membeli saham.'},{title:'Isi Jumlah Lot Pertama',desc:'Berapa lot yang dibeli pada transaksi pertama.'},{title:'Isi Harga Beli Berikutnya',desc:'Masukkan harga saat kamu menambah posisi — lebih rendah untuk average down, lebih tinggi untuk average up.'},{title:'Isi Jumlah Lot Berikutnya',desc:'Berapa lot yang ditambahkan pada transaksi kedua.'},{title:'Baca Hasilnya',desc:'Harga rata-rata muncul otomatis. Ini adalah harga break-even baru kamu sebelum biaya fee.'}]}
      formula={"Avg Harga = (Harga1 × Lot1 + Harga2 × Lot2) / (Lot1 + Lot2)\nTotal Nilai = Avg Harga × Total Lot × 100 (1 lot = 100 lembar)"}
      formulaExample={"Beli 10 lot @ Rp 5.000 = Rp 5.000.000\nTambah 10 lot @ Rp 4.000 = Rp 4.000.000\nAverage = (5.000.000 + 4.000.000) / (20 × 100) = Rp 4.500"}
      variables={[{name:'Harga1',desc:'Harga per lembar pada pembelian pertama'},{name:'Lot1',desc:'Jumlah lot pada pembelian pertama (1 lot = 100 lembar)'},{name:'Harga2',desc:'Harga per lembar pada pembelian tambahan'},{name:'Lot2',desc:'Jumlah lot pada pembelian tambahan'},{name:'Avg Harga',desc:'Harga rata-rata tertimbang dari kedua posisi'}]}
      history={"Strategi averaging digunakan investor sejak pasar saham modern terbentuk di abad ke-19. Benjamin Graham, mentor Warren Buffett, membahas konsep ini secara mendalam dalam The Intelligent Investor (1949) sebagai salah satu cara disiplin untuk mengelola posisi yang sedang merugi.\n\nAverage down populer di kalangan investor nilai (value investor) yang percaya bahwa penurunan harga sementara menciptakan kesempatan beli lebih banyak dengan harga lebih murah. Namun strategi ini membutuhkan keyakinan kuat terhadap fundamental perusahaan.\n\nPeter Lynch dalam buku One Up on Wall Street (1989) mengingatkan bahwa average down hanya layak dilakukan jika alasan awal membeli saham masih valid — bukan sekadar karena harga sudah turun jauh."}
      faqs={[{q:'Kapan sebaiknya melakukan average down?',a:'Average down layak dilakukan jika fundamental perusahaan masih kuat, penurunan harga disebabkan sentimen pasar bukan masalah bisnis, dan kamu punya modal cadangan yang tidak akan dibutuhkan dalam waktu dekat. Jangan average down hanya karena rugi — pastikan alasan awal kamu membeli masih valid.'},{q:'Apakah average up menguntungkan?',a:'Average up berarti menambah posisi di harga lebih tinggi. Ini lazim dilakukan trader momentum yang percaya trend akan berlanjut. Risikonya: jika harga berbalik, harga rata-rata yang lebih tinggi membuat kerugian lebih besar.'},{q:'Berapa lot maksimum yang ideal untuk averaging?',a:'Tidak ada angka pasti — bergantung pada manajemen risiko kamu. Aturan umum: total posisi satu saham tidak lebih dari 10–20% dari total portofolio. Gunakan Risk Manager atau Entry Price Optimizer untuk menentukan lot yang aman.'},{q:'Bagaimana menghitung harga break-even setelah averaging?',a:'Harga break-even setelah fee bisa berbeda dari harga rata-rata murni. Gunakan Break-even Analyzer untuk memperhitungkan biaya fee beli dan jual broker secara akurat.'}]}
      related={[{name:'Break-even Analyzer',href:'/saham/break-even-analyzer',desc:'Hitung harga jual minimum untuk balik modal setelah fee broker'},{name:'Entry Price Optimizer',href:'/saham/entry-price-optimizer',desc:'Tentukan lot optimal berdasarkan modal dan risiko sebelum averaging'},{name:'Risk Manager',href:'/trading/risk-manager',desc:'Hitung ukuran posisi yang aman sebelum menambah posisi saham'},{name:'Trade Analyzer',href:'/trading/trade-analyzer',desc:'Analisis R/R ratio setelah menentukan target harga dan stop loss'}]}
      references={['Graham, B. (1949). <em>The Intelligent Investor.</em> Harper & Brothers.','Lynch, P. (1989). <em>One Up on Wall Street.</em> Simon & Schuster.','IDX. <em>Panduan Investasi Saham.</em> <a href="https://idx.co.id" target="_blank" rel="noopener noreferrer" class="text-finc-green hover:underline">idx.co.id</a>']}
    ><AveragingStrategyBuilder /></SahamToolPage>
  </main><Footer /></>)
}
