import type { Metadata } from 'next'
import Link from 'next/link'
import { ChevronRight } from 'lucide-react'
import Header from '@/components/layout/Header'
import Footer from '@/components/layout/Footer'
import PersonalFinanceToolPage from '@/components/layout/PersonalFinanceToolPage'
import DebtDestroyer from '@/components/tools/personal-finance/DebtDestroyer'
export const metadata: Metadata = { title: 'Debt Destroyer — Strategi Pelunasan Utang Optimal | FincTools', description: 'Bandingkan strategi Avalanche vs Snowball untuk melunasi utang lebih cepat dan hemat bunga.' }
export default function Page() {
  return (<><Header /><main className="mx-auto max-w-4xl px-4 py-8">
    <nav className="flex items-center gap-1 text-xs text-[--text-secondary] mb-6"><Link href="/" className="hover:text-finc-green">Home</Link><ChevronRight size={12}/><Link href="/personal-finance" className="hover:text-finc-green">Personal Finance</Link><ChevronRight size={12}/><span className="text-[--text-primary] font-medium">Debt Destroyer</span></nav>
    <PersonalFinanceToolPage name="Debt Destroyer" subcategory="Manajemen Utang"
      description="Debt Destroyer membantu memilih strategi pelunasan utang yang paling efektif: Avalanche (lunasi bunga tertinggi dahulu untuk hemat biaya) atau Snowball (lunasi saldo terkecil dahulu untuk motivasi psikologis)."
      steps={[{title:'Lihat Daftar Utang Default',desc:'Tool sudah menyediakan contoh 3 utang umum. Kamu bisa melihat visualisasi urutan pelunasan langsung.'},{title:'Tambahkan Pembayaran Ekstra',desc:'Masukkan berapa tambahan yang bisa kamu bayarkan di atas cicilan minimum setiap bulan — ini kunci mempercepat pelunasan.'},{title:'Bandingkan Dua Metode',desc:'Avalanche melunasi bunga tertinggi dahulu — hemat biaya total. Snowball melunasi saldo terkecil dahulu — lebih banyak kemenangan kecil untuk motivasi.'},{title:'Pilih Metode yang Cocok',desc:'Jika motivasi kamu kuat, pilih Avalanche. Jika butuh "kemenangan" cepat untuk tetap semangat, pilih Snowball.'}]}
      formula={"Metode Avalanche: Urutkan utang dari bunga tertinggi ke terendah\nBayar minimum semua utang + ekstra ke utang bunga tertinggi\nSetelah lunas, alihkan seluruh pembayaran ke utang berikutnya\n\nMetode Snowball: Urutkan dari saldo terkecil ke terbesar\nStrategi pembayaran sama, urutan target berbeda"}
      formulaExample={"Utang 3 jenis: KPR 8%, Mobil 12%, Kartu Kredit 24%\nAvalanche: CC dulu → Mobil → KPR\nSnowball: tergantung saldo (yang terkecil dahulu)\nDengan tambahan Rp 1.000.000/bulan, CC lunas dalam ~15 bulan"}
      variables={[{name:'Avalanche',desc:'Metode pelunasan dengan mendahulukan utang berbunga tertinggi — matematically optimal'},{name:'Snowball',desc:'Metode pelunasan dengan mendahulukan saldo terkecil — optimal secara psikologis'},{name:'Tambahan Pembayaran',desc:'Jumlah di atas cicilan minimum yang dialokasikan sebagai "peluru" untuk melunasi lebih cepat'}]}
      history={"Debt Avalanche Method secara matematis dibuktikan oleh ahli keuangan sebagai cara paling efisien melunasi utang karena meminimalkan total bunga yang dibayarkan. Namun penelitian perilaku keuangan menunjukkan bahwa manusia tidak selalu rasional.\n\nDebt Snowball Method dipopulerkan oleh Dave Ramsey dalam The Total Money Makeover (2003). Ramsey berargumen bahwa motivasi dan momentum psikologis lebih penting daripada optimasi matematika — orang lebih mungkin menyelesaikan proses jika merasakan 'kemenangan' awal lebih cepat.\n\nPenelitian oleh Amar, Ariely, Ayal, dan Cryder (2011) dalam Journal of Marketing Research menemukan bahwa orang lebih termotivasi melunasi utang saat melihat jumlah utang yang berkurang secara signifikan — mendukung efektivitas psikologis metode Snowball."}
      faqs={[{q:'Metode mana yang lebih baik, Avalanche atau Snowball?',a:'Avalanche lebih baik secara matematika — menghemat lebih banyak bunga. Snowball lebih baik secara psikologi — memberikan motivasi dari kemenangan kecil yang cepat. Pilih berdasarkan karakter dirimu: apakah kamu tipe yang butuh hasil cepat untuk tetap termotivasi, atau bisa sabar dengan pendekatan optimal jangka panjang?'},{q:'Berapa banyak tambahan pembayaran yang ideal?',a:'Semakin besar semakin baik — setiap tambahan pembayaran langsung mengurangi pokok utang dan memotong bunga di bulan-bulan berikutnya. Bahkan Rp 200.000 ekstra per bulan bisa memangkas waktu pelunasan berbulan-bulan.'},{q:'Apakah melunasi utang lebih baik dari berinvestasi?',a:'Jika bunga utang > return investasi yang diharapkan, lunasi utang dahulu. Kartu kredit dengan bunga 24% per tahun jauh lebih mahal dari return reksa dana 15%/tahun. Namun tetap pertahankan investasi minimal untuk dana pensiun dan manfaatkan employer matching jika ada.'},{q:'Bagaimana jika penghasilan tidak stabil?',a:'Tetapkan minimum pembayaran semua utang sebagai angka yang wajib dipenuhi. Tambahan pembayaran baru dilakukan jika ada kelebihan penghasilan di bulan itu. Yang terpenting: jangan pernah melewati cicilan minimum untuk menghindari denda dan kerusakan skor kredit.'}]}
      related={[{name:'Budget Architect',href:'/personal-finance/budget-architect',desc:'Susun anggaran untuk mengidentifikasi dana yang bisa dialihkan ke pelunasan utang'},{name:'Loan True Cost Analyzer',href:'/kredit-properti/loan-true-cost-analyzer',desc:'Hitung total biaya sebenarnya dari setiap utang yang kamu miliki'},{name:'Net Worth Tracker',href:'/personal-finance/net-worth-tracker',desc:'Pantau kemajuan nett worth kamu saat utang berkurang'},{name:'Savings Growth Simulator',href:'/personal-finance/savings-growth-simulator',desc:'Proyeksikan pertumbuhan tabungan setelah semua utang lunas'}]}
      references={['Ramsey, D. (2003). <em>The Total Money Makeover.</em> Thomas Nelson.','Amar, M. et al. (2011). Winning the Battle but Losing the War. <em>Journal of Marketing Research.</em>','OJK. <em>Panduan Pengelolaan Utang.</em> <a href="https://ojk.go.id" target="_blank" rel="noopener noreferrer" class="text-finc-green hover:underline">ojk.go.id</a>']}
    ><DebtDestroyer /></PersonalFinanceToolPage>
  </main><Footer /></>)
}
