import type { Metadata } from 'next'
import Link from 'next/link'
import { ChevronRight } from 'lucide-react'
import Header from '@/components/layout/Header'
import Footer from '@/components/layout/Footer'
import KriptoToolPage from '@/components/layout/KriptoToolPage'
import FundingRateCostEstimator from '@/components/tools/kripto/FundingRateCostEstimator'
export const metadata: Metadata = { title: 'Funding Rate Cost Estimator | FincTools', description: 'Estimasi total biaya funding rate untuk posisi futures yang dipertahankan beberapa hari.' }
export default function Page() {
  return (<><Header /><main className="mx-auto max-w-4xl px-4 py-8">
    <nav className="flex items-center gap-1 text-xs text-[--text-secondary] mb-6"><Link href="/" className="hover:text-finc-green">Home</Link><ChevronRight size={12}/><Link href="/kripto" className="hover:text-finc-green">Kripto</Link><ChevronRight size={12}/><span className="text-[--text-primary] font-medium">Funding Rate Cost Estimator</span></nav>
    <KriptoToolPage name="Funding Rate Cost Estimator" description="Estimasi total biaya funding rate untuk posisi futures yang dipertahankan beberapa hari."
      steps={[{title:'Isi data aset kripto',desc:'Masukkan data posisi atau investasi kripto kamu pada field yang tersedia.'},{title:'Sesuaikan parameter',desc:'Gunakan slider atau input angka untuk mengubah variabel sesuai kondisi aktual.'},{title:'Baca hasilnya',desc:'Semua kalkulasi berjalan real-time di browser kamu.'},{title:'Gunakan sebagai referensi',desc:'Kripto sangat berisiko. Selalu lakukan riset mandiri dan jangan investasi lebih dari yang siap kamu rugikan.'}]}
      formula="Kalkulasi menggunakan formula standar yang digunakan exchange kripto terkemuka."
      variables={[{name:'Input Kripto',desc:'Semua variabel disesuaikan kebutuhan spesifik tool ini'},{name:'Output',desc:'Hasil kalkulasi real-time untuk manajemen posisi kripto'}]}
      history="Funding rate adalah mekanisme unik pada perpetual futures kripto yang tidak ada di pasar futures konvensional. Diperkenalkan oleh BitMEX sekitar 2016, mekanisme ini memastikan harga perpetual futures tetap mendekati harga spot dengan memberikan atau menagih biaya antara holder Long dan Short setiap 8 jam.\n\nKetika pasar bullish ekstrem, Long membayar Short funding rate yang sangat tinggi (bisa mencapai 0.1% per 8 jam = ~109% per tahun). Sebaliknya saat bearish, Short yang membayar Long. Funding rate menjadi indikator sentiment pasar yang digunakan banyak trader.\n\nDi Indonesia, akses perpetual futures kripto sudah tersedia melalui exchange internasional. OJK sedang dalam proses regulasi derivatif kripto, sehingga status hukumnya masih dalam area abu-abu."
      faqs={[{q:'Funding rate positif atau negatif, mana yang lebih baik?',a:'Tergantung posisimu. Funding positif berarti Long membayar Short — menguntungkan jika kamu Short. Funding negatif berarti Short membayar Long — menguntungkan jika kamu Long. Beberapa strategi 'funding rate farming' sengaja mengambil posisi berlawanan arah untuk mengumpulkan funding rate.'},{q:'Berapa funding rate yang normal vs tidak normal?',a:'Funding rate normal umumnya ±0.01% per 8 jam. Funding >0.05%/8jam dianggap sangat bullish. Funding <-0.05%/8jam dianggap sangat bearish. Funding ekstrem sering menjadi tanda reversal pasar karena posisi terlalu berat ke satu sisi.'},{q:'Apakah tool ini berlaku untuk semua exchange kripto?',a:'Formula dasar berlaku universal, namun setiap exchange memiliki parameter sedikit berbeda (terutama maintenance margin dan insurance fund). Gunakan sebagai estimasi dan verifikasi dengan kalkulator bawaan exchange yang kamu gunakan.'},{q:'Apakah trading kripto dengan leverage direkomendasikan untuk pemula?',a:'Sangat tidak direkomendasikan. Leverage memperbesar keuntungan dan kerugian secara proporsional. Mulai dengan spot trading tanpa leverage, pahami pergerakan harga, sebelum mempertimbangkan futures.'}]}
      related={[{name:'Crypto DCA Simulator',href:'/kripto/crypto-dca-simulator',desc:'Strategi lebih aman untuk investasi kripto jangka panjang'},{name:'Crypto Risk Manager',href:'/kripto/crypto-risk-manager',desc:'Hitung position sizing yang aman untuk trading kripto'},{name:'Risk Manager',href:'/trading/risk-manager',desc:'Versi risk manager untuk forex dan instrumen trading lain'},{name:'DCA Simulator',href:'/investasi/dca-simulator',desc:'Simulasi DCA untuk reksa dana dan saham yang lebih konservatif'}]}
      references={['Nakamoto, S. (2008). <em>Bitcoin: A Peer-to-Peer Electronic Cash System.</em>','OJK. <em>Peraturan Aset Kripto.</em> <a href="https://ojk.go.id" target="_blank" rel="noopener noreferrer" class="text-finc-green hover:underline">ojk.go.id</a>','Bappebti. <em>Regulasi Perdagangan Aset Kripto.</em> <a href="https://bappebti.go.id" target="_blank" rel="noopener noreferrer" class="text-finc-green hover:underline">bappebti.go.id</a>']}
    ><FundingRateCostEstimator /></KriptoToolPage>
  </main><Footer /></>)
}
