import type { Metadata } from 'next'
import Link from 'next/link'
import { ChevronRight } from 'lucide-react'
import Header from '@/components/layout/Header'
import Footer from '@/components/layout/Footer'
import KriptoToolPage from '@/components/layout/KriptoToolPage'
import LiquidationPriceAnalyzer from '@/components/tools/kripto/LiquidationPriceAnalyzer'
export const metadata: Metadata = { title: 'Liquidation Price Analyzer | FincTools', description: 'Kalkulasi harga likuidasi posisi futures kripto berdasarkan leverage dan maintenance margin.' }
export default function Page() {
  return (<><Header /><main className="mx-auto max-w-4xl px-4 py-8">
    <nav className="flex items-center gap-1 text-xs text-[--text-secondary] mb-6"><Link href="/" className="hover:text-finc-green">Home</Link><ChevronRight size={12}/><Link href="/kripto" className="hover:text-finc-green">Kripto</Link><ChevronRight size={12}/><span className="text-[--text-primary] font-medium">Liquidation Price Analyzer</span></nav>
    <KriptoToolPage name="Liquidation Price Analyzer" description="Kalkulasi harga likuidasi posisi futures kripto berdasarkan leverage dan maintenance margin."
      steps={[{title:'Isi data aset kripto',desc:'Masukkan data posisi atau investasi kripto kamu pada field yang tersedia.'},{title:'Sesuaikan parameter',desc:'Gunakan slider atau input angka untuk mengubah variabel sesuai kondisi aktual.'},{title:'Baca hasilnya',desc:'Semua kalkulasi berjalan real-time di browser kamu.'},{title:'Gunakan sebagai referensi',desc:'Kripto sangat berisiko. Selalu lakukan riset mandiri dan jangan investasi lebih dari yang siap kamu rugikan.'}]}
      formula="Kalkulasi menggunakan formula standar yang digunakan exchange kripto terkemuka."
      variables={[{name:'Input Kripto',desc:'Semua variabel disesuaikan kebutuhan spesifik tool ini'},{name:'Output',desc:'Hasil kalkulasi real-time untuk manajemen posisi kripto'}]}
      history="Likuidasi dalam trading futures kripto terjadi ketika margin trader tidak mencukupi untuk menanggung kerugian mark-to-market. Konsep ini diadaptasi dari pasar futures tradisional di mana exchange menjadi counterparty.\n\nPada crash kripto Mei 2021 dan November 2022, miliaran dolar posisi futures dilikuidasi dalam hitungan jam — menciptakan efek domino yang mempercepat penurunan harga. Data dari Coinglass menunjukkan likuidasi terbesar dalam sejarah kripto mencapai > miliar dalam 24 jam.\n\nBinance, OKX, dan Bybit menggunakan rumus maintenance margin yang sedikit berbeda. Selalu cek rumus spesifik exchange yang kamu gunakan karena perbedaan kecil bisa berdampak signifikan pada harga likuidasi aktual."
      faqs={[{q:'Apa yang terjadi saat posisi dilikuidasi?',a:'Exchange secara paksa menutup posisimu saat margin tidak mencukupi. Semua modal di posisi tersebut bisa hilang. Beberapa exchange memberikan 'liquidation price' dan 'bankruptcy price' yang berbeda — bankrupcy price adalah titik di mana seluruh modal awal habis.'},{q:'Bagaimana cara menghindari likuidasi?',a:'Gunakan leverage rendah (idealnya maksimal 3–5x untuk pemula), pasang stop loss jauh sebelum harga likuidasi, dan jangan menggunakan seluruh modal sebagai margin. Sisakan setidaknya 50% modal di luar posisi sebagai buffer jika ingin menambah margin.'},{q:'Apakah tool ini berlaku untuk semua exchange kripto?',a:'Formula dasar berlaku universal, namun setiap exchange memiliki parameter sedikit berbeda (terutama maintenance margin dan insurance fund). Gunakan sebagai estimasi dan verifikasi dengan kalkulator bawaan exchange yang kamu gunakan.'},{q:'Apakah trading kripto dengan leverage direkomendasikan untuk pemula?',a:'Sangat tidak direkomendasikan. Leverage memperbesar keuntungan dan kerugian secara proporsional. Mulai dengan spot trading tanpa leverage, pahami pergerakan harga, sebelum mempertimbangkan futures.'}]}
      related={[{name:'Crypto DCA Simulator',href:'/kripto/crypto-dca-simulator',desc:'Strategi lebih aman untuk investasi kripto jangka panjang'},{name:'Crypto Risk Manager',href:'/kripto/crypto-risk-manager',desc:'Hitung position sizing yang aman untuk trading kripto'},{name:'Risk Manager',href:'/trading/risk-manager',desc:'Versi risk manager untuk forex dan instrumen trading lain'},{name:'DCA Simulator',href:'/investasi/dca-simulator',desc:'Simulasi DCA untuk reksa dana dan saham yang lebih konservatif'}]}
      references={['Nakamoto, S. (2008). <em>Bitcoin: A Peer-to-Peer Electronic Cash System.</em>','OJK. <em>Peraturan Aset Kripto.</em> <a href="https://ojk.go.id" target="_blank" rel="noopener noreferrer" class="text-finc-green hover:underline">ojk.go.id</a>','Bappebti. <em>Regulasi Perdagangan Aset Kripto.</em> <a href="https://bappebti.go.id" target="_blank" rel="noopener noreferrer" class="text-finc-green hover:underline">bappebti.go.id</a>']}
    ><LiquidationPriceAnalyzer /></KriptoToolPage>
  </main><Footer /></>)
}
