import type { Metadata } from 'next'
import Link from 'next/link'
import { ChevronRight } from 'lucide-react'
import Header from '@/components/layout/Header'
import Footer from '@/components/layout/Footer'
import PersonalFinanceToolPage from '@/components/layout/PersonalFinanceToolPage'
import EmergencyShieldBuilder from '@/components/tools/personal-finance/EmergencyShieldBuilder'
export const metadata: Metadata = { title: 'Emergency Shield Builder — Kalkulasi Dana Darurat | FincTools', description: 'Kalkulasi dana darurat ideal berdasarkan pengeluaran bulanan dan status pekerjaan, serta estimasi waktu mencapai target.' }
export default function Page() {
  return (<><Header /><main className="mx-auto max-w-4xl px-4 py-8">
    <nav className="flex items-center gap-1 text-xs text-[--text-secondary] mb-6"><Link href="/" className="hover:text-finc-green">Home</Link><ChevronRight size={12}/><Link href="/personal-finance" className="hover:text-finc-green">Personal Finance</Link><ChevronRight size={12}/><span className="text-[--text-primary] font-medium">Emergency Shield Builder</span></nav>
    <PersonalFinanceToolPage name="Emergency Shield Builder" subcategory="Dana Darurat"
      description="Emergency Shield Builder menghitung jumlah dana darurat yang ideal berdasarkan pengeluaran bulanan dan status pekerjaan, sekaligus memproyeksikan berapa lama waktu yang dibutuhkan untuk mencapai target."
      steps={[{title:'Isi Pengeluaran Bulanan',desc:'Masukkan total pengeluaran wajib per bulan — kebutuhan pokok, cicilan, tagihan, dan biaya rutin lainnya.'},{title:'Set Target Bulan Dana Darurat',desc:'3 bulan untuk karyawan tetap, 6 bulan untuk karyawan kontrak/freelancer, 12 bulan untuk pengusaha atau yang menanggung keluarga.'},{title:'Isi Dana yang Sudah Tersimpan',desc:'Berapa dana yang sudah kamu sisihkan khusus sebagai dana darurat saat ini.'},{title:'Isi Tabungan per Bulan',desc:'Berapa yang akan kamu alokasikan setiap bulan untuk menambah dana darurat.'},{title:'Baca Statusnya',desc:'Persentase terpenuhi dan estimasi bulan untuk mencapai target ditampilkan. Warna hijau berarti sudah cukup.'}]}
      formula={"Target Dana Darurat = Pengeluaran Bulanan × Jumlah Bulan Target\nKekurangan = Target - Dana yang Sudah Ada\nEstimasi Bulan = ⌈Kekurangan / Tabungan per Bulan⌉\n% Terpenuhi = (Dana Ada / Target) × 100"}
      formulaExample={"Pengeluaran Rp 10.000.000/bln | Target 6 bulan | Ada Rp 20.000.000\nTarget = Rp 60.000.000\nKekurangan = Rp 40.000.000\nDengan tabungan Rp 2.000.000/bln → 20 bulan lagi"}
      variables={[{name:'Target Bulan',desc:'Berapa bulan pengeluaran yang harus bisa ditanggung tanpa penghasilan'},{name:'Kekurangan',desc:'Selisih antara target dana darurat dan dana yang sudah tersedia'},{name:'% Terpenuhi',desc:'Persentase kemajuan menuju target dana darurat yang ideal'}]}
      history={"Konsep dana darurat dipopulerkan oleh Dave Ramsey melalui program radio dan bukunya The Total Money Makeover (2003) sebagai Baby Step pertama dari tujuh langkah menuju kebebasan finansial.\n\nSecara historis, aturan 3–6 bulan pengeluaran berasal dari studi perilaku ekonomi yang menemukan bahwa rata-rata pencari kerja di AS membutuhkan 3–6 bulan untuk mendapatkan pekerjaan baru. Di Indonesia, BPS mencatat rata-rata durasi mencari kerja yang lebih bervariasi tergantung sektor dan lokasi.\n\nSelama pandemi COVID-19 (2020–2021), banyak keluarga Indonesia yang tidak memiliki dana darurat terpaksa menjual aset investasi di harga rendah untuk memenuhi kebutuhan hidup. Ini memperkuat pentingnya dana darurat sebagai fondasi keuangan yang tidak bisa dilewati."}
      faqs={[{q:'Berapa bulan dana darurat yang ideal?',a:'3 bulan untuk karyawan tetap dengan penghasilan stabil. 6 bulan untuk karyawan kontrak, freelancer, atau yang memiliki tanggungan keluarga. 9–12 bulan untuk pengusaha, karena pendapatan bisnis lebih tidak pasti.'},{q:'Di mana sebaiknya menyimpan dana darurat?',a:'Dana darurat harus mudah diakses kapanpun dibutuhkan. Pilihan terbaik: reksa dana pasar uang (return lebih tinggi dari tabungan, bisa dicairkan dalam 1–2 hari), tabungan di bank berbeda dari rekening utama, atau deposito dengan tanggal jatuh tempo berjenjang.'},{q:'Apakah dana darurat perlu dipisah dari tabungan biasa?',a:'Sangat disarankan. Pisahkan di rekening atau instrumen berbeda agar tidak tergoda menggunakannya untuk kebutuhan lain. Anggap dana darurat sebagai "tidak ada" sampai benar-benar darurat.'},{q:'Apa yang termasuk darurat dan apa yang bukan?',a:'Darurat adalah situasi mendesak tak terduga yang mengancam kelangsungan hidup atau pekerjaan: sakit mendadak, kehilangan pekerjaan, kerusakan kendaraan yang wajib untuk bekerja. Bukan darurat: liburan, gadget baru, atau diskon belanja.'}]}
      related={[{name:'Savings Growth Simulator',href:'/personal-finance/savings-growth-simulator',desc:'Proyeksikan pertumbuhan dana darurat dengan bunga reksa dana pasar uang'},{name:'Goal Achiever Planner',href:'/personal-finance/goal-achiever-planner',desc:'Hitung tabungan per bulan untuk mencapai target dana darurat'},{name:'Budget Architect',href:'/personal-finance/budget-architect',desc:'Rencanakan anggaran agar ada alokasi rutin untuk dana darurat'},{name:'Wealth Freedom Planner',href:'/personal-finance/wealth-freedom-planner',desc:'Setelah dana darurat cukup, mulai rencanakan kebebasan finansial'}]}
      references={['Ramsey, D. (2003). <em>The Total Money Makeover.</em> Thomas Nelson.','BPS. <em>Keadaan Ketenagakerjaan Indonesia.</em> <a href="https://bps.go.id" target="_blank" rel="noopener noreferrer" class="text-finc-green hover:underline">bps.go.id</a>','OJK. <em>Panduan Perencanaan Keuangan.</em> <a href="https://ojk.go.id" target="_blank" rel="noopener noreferrer" class="text-finc-green hover:underline">ojk.go.id</a>']}
    ><EmergencyShieldBuilder /></PersonalFinanceToolPage>
  </main><Footer /></>)
}
