import type { Metadata } from 'next'
import Link from 'next/link'
import { ChevronRight } from 'lucide-react'
import Header from '@/components/layout/Header'
import Footer from '@/components/layout/Footer'
import PersonalFinanceToolPage from '@/components/layout/PersonalFinanceToolPage'
import BudgetArchitect from '@/components/tools/personal-finance/BudgetArchitect'
export const metadata: Metadata = { title: 'Budget Architect — Perencanaan Anggaran 50-30-20 | FincTools', description: 'Rencanakan anggaran bulanan dengan aturan 50-30-20 yang fleksibel dan dapat disesuaikan kondisi keuanganmu.' }
export default function Page() {
  return (<><Header /><main className="mx-auto max-w-4xl px-4 py-8">
    <nav className="flex items-center gap-1 text-xs text-[--text-secondary] mb-6"><Link href="/" className="hover:text-finc-green">Home</Link><ChevronRight size={12}/><Link href="/personal-finance" className="hover:text-finc-green">Personal Finance</Link><ChevronRight size={12}/><span className="text-[--text-primary] font-medium">Budget Architect</span></nav>
    <PersonalFinanceToolPage name="Budget Architect" subcategory="Perencanaan Anggaran"
      description="Budget Architect membantu merancang anggaran bulanan berdasarkan aturan 50-30-20 — 50% untuk kebutuhan, 30% untuk keinginan, 20% untuk tabungan dan investasi — dengan alokasi yang dapat disesuaikan."
      steps={[{title:'Isi Penghasilan Bersih',desc:'Masukkan take home pay setelah pajak dan potongan wajib — jumlah yang benar-benar masuk ke rekening kamu setiap bulan.'},{title:'Sesuaikan Persentase Kebutuhan',desc:'Kebutuhan adalah pengeluaran wajib: makan, tempat tinggal, transportasi, listrik, cicilan. Standar 50%, tapi bisa lebih tinggi untuk yang tinggal di kota besar.'},{title:'Sesuaikan Persentase Keinginan',desc:'Keinginan adalah pengeluaran yang membuat hidup lebih menyenangkan: makan di luar, hiburan, belanja. Standar 30%.'},{title:'Cek Alokasi Tabungan',desc:'Pastikan minimal 20% dari penghasilan masuk ke tabungan dan investasi. Ini adalah bagian paling penting untuk masa depan.'},{title:'Implementasikan',desc:'Buat rekening terpisah atau amplop digital untuk masing-masing kategori agar anggaran mudah dijalankan.'}]}
      formula={"Kebutuhan = Penghasilan × Kebutuhan%\nKeinginan = Penghasilan × Keinginan%\nTabungan = Penghasilan × Tabungan%\nTotal = Kebutuhan% + Keinginan% + Tabungan% = 100%"}
      formulaExample={"Penghasilan bersih Rp 10.000.000/bulan\n50% Kebutuhan = Rp 5.000.000 (makan, kos, transport, cicilan)\n30% Keinginan = Rp 3.000.000 (nongkrong, hiburan, belanja)\n20% Tabungan  = Rp 2.000.000 (investasi, dana darurat)"}
      variables={[{name:'Kebutuhan (50%)',desc:'Pengeluaran wajib yang tidak bisa dihindari — kebutuhan hidup dasar dan kewajiban finansial'},{name:'Keinginan (30%)',desc:'Pengeluaran yang meningkatkan kualitas hidup namun bisa dikurangi jika perlu'},{name:'Tabungan (20%)',desc:'Alokasi untuk masa depan — dana darurat, investasi, dan tujuan finansial jangka panjang'}]}
      history={"Aturan 50-30-20 dipopulerkan oleh Senator AS dan pakar kebangkrutan Elizabeth Warren bersama putrinya Amelia Warren Tyagi dalam buku All Your Worth: The Ultimate Lifetime Money Plan (2005). Warren mengembangkan framework ini dari penelitiannya tentang pola pengeluaran keluarga Amerika selama 20 tahun.\n\nSebelum 50-30-20, budgeting tradisional menggunakan sistem amplop (envelope method) yang dipopulerkan Dave Ramsey — memisahkan uang tunai ke dalam amplop fisik untuk setiap kategori pengeluaran.\n\nDi era digital, konsep ini diadaptasi ke aplikasi keuangan dan sistem rekening terpisah. Di Indonesia, platform seperti Jenius dan Flip memungkinkan pembuatan 'kantong' atau 'pocket' virtual yang memudahkan implementasi sistem 50-30-20."}
      faqs={[{q:'Bagaimana jika kebutuhan saya sudah melebihi 50%?',a:'Ini umum terutama di kota besar dengan biaya sewa tinggi. Sesuaikan persentase — misalnya 60-20-20 atau bahkan 70-10-20. Yang terpenting: tetap ada alokasi untuk tabungan, meski kecil. Tingkatkan secara bertahap saat penghasilan naik.'},{q:'Apakah cicilan KPR masuk kebutuhan atau keinginan?',a:'KPR masuk kategori kebutuhan karena merupakan kewajiban finansial bulanan yang tidak bisa dilewati. Hal yang sama berlaku untuk cicilan kendaraan yang digunakan untuk bekerja dan premi asuransi.'},{q:'Bagaimana cara memulai budgeting jika selama ini tidak pernah?',a:'Mulai dengan mencatat semua pengeluaran selama 1 bulan tanpa mengubah apapun. Ini memberikan gambaran akurat ke mana uang kamu pergi selama ini. Baru setelah itu terapkan 50-30-20 dan sesuaikan bertahap.'},{q:'Apakah 20% untuk tabungan bisa digunakan untuk cicilan utang?',a:'Jika punya utang berbunga tinggi seperti kartu kredit, sebagian alokasi 20% bisa digunakan untuk melunasi lebih cepat. Namun tetap sisihkan minimal 5–10% untuk dana darurat dan investasi — mulai dari yang kecil.'}]}
      related={[{name:'Debt Destroyer',href:'/personal-finance/debt-destroyer',desc:'Strategi melunasi utang agar alokasi tabungan bisa ditingkatkan'},{name:'Emergency Shield Builder',href:'/personal-finance/emergency-shield-builder',desc:'Pastikan alokasi tabungan cukup untuk membangun dana darurat'},{name:'Goal Achiever Planner',href:'/personal-finance/goal-achiever-planner',desc:'Hitung apakah alokasi 20% cukup untuk mencapai tujuan finansialmu'},{name:'Savings Growth Simulator',href:'/personal-finance/savings-growth-simulator',desc:'Proyeksikan pertumbuhan dari alokasi tabungan 20% selama bertahun-tahun'}]}
      references={['Warren, E. & Tyagi, A.W. (2005). <em>All Your Worth: The Ultimate Lifetime Money Plan.</em> Free Press.','Ramsey, D. (2003). <em>The Total Money Makeover.</em> Thomas Nelson.','OJK. <em>Panduan Perencanaan Keuangan Keluarga.</em> <a href="https://ojk.go.id" target="_blank" rel="noopener noreferrer" class="text-finc-green hover:underline">ojk.go.id</a>']}
    ><BudgetArchitect /></PersonalFinanceToolPage>
  </main><Footer /></>)
}
