import type { Metadata } from 'next'
import Link from 'next/link'
import { ChevronRight } from 'lucide-react'
import Header from '@/components/layout/Header'
import Footer from '@/components/layout/Footer'
import KreditToolPage from '@/components/layout/KreditToolPage'
import KPRAffordabilityChecker from '@/components/tools/kredit/KPRAffordabilityChecker'
export const metadata: Metadata = { title: 'KPR Affordability Checker — Cek Kemampuan Cicilan KPR | FincTools', description: 'Cek kemampuan cicilan KPR maksimum berdasarkan penghasilan bersih, cicilan existing, dan debt-to-income ratio 35%.' }
export default function Page() {
  return (<><Header /><main className="mx-auto max-w-4xl px-4 py-8">
    <nav className="flex items-center gap-1 text-xs text-[--text-secondary] mb-6"><Link href="/" className="hover:text-finc-green">Home</Link><ChevronRight size={12}/><Link href="/kredit-properti" className="hover:text-finc-green">Kredit & Properti</Link><ChevronRight size={12}/><span className="text-[--text-primary] font-medium">KPR Affordability Checker</span></nav>
    <KreditToolPage name="KPR Affordability Checker" subcategory="Perencanaan KPR"
      description="KPR Affordability Checker menghitung harga properti maksimum yang bisa kamu beli melalui KPR berdasarkan penghasilan bersih, cicilan yang sudah ada, bunga KPR, dan down payment — menggunakan standar DTI 35% yang umum digunakan perbankan Indonesia."
      steps={[{title:'Isi Penghasilan Bersih Bulanan',desc:'Masukkan take home pay atau penghasilan bersih setelah pajak dan potongan wajib. Untuk suami-istri bekerja, bisa digabungkan.'},{title:'Isi Total Cicilan yang Sudah Ada',desc:'Semua cicilan aktif selain KPR baru: cicilan motor/mobil, kartu kredit, KTA, atau pinjaman lain. Ini mengurangi kapasitas KPR.'},{title:'Set Bunga dan Tenor KPR',desc:'Bunga KPR bank konvensional Indonesia saat ini sekitar 8–12%/tahun. Tenor maksimum umumnya 30 tahun. Suku bunga fixed biasanya berlaku 1–5 tahun pertama.'},{title:'Set Down Payment',desc:'Minimum DP KPR di Indonesia 10–20% dari harga properti tergantung jenis rumah dan kebijakan bank.'},{title:'Baca Kemampuan KPR',desc:'Harga properti maksimum, cicilan KPR maksimum, pinjaman maksimum, dan DP yang dibutuhkan ditampilkan lengkap.'}]}
      formula={"Max Cicilan Total = Penghasilan × 35% (DTI)\nMax Cicilan KPR = Max Cicilan Total - Cicilan Existing\nMax Pinjaman = Max Cicilan KPR × ((1+r)^n - 1) / (r × (1+r)^n)\nMax Harga Properti = Max Pinjaman / (1 - DP%)\nDP Dibutuhkan = Max Harga × DP%"}
      formulaExample={"Penghasilan Rp 15jt | Cicilan Lain Rp 2jt | Bunga 10% | Tenor 20thn | DP 20%\nMax Cicilan = Rp 5.250.000 (35% dari 15jt)\nMax Cicilan KPR = Rp 3.250.000 (5.25jt - 2jt)\nMax Pinjaman ≈ Rp 337.000.000\nMax Harga = Rp 421.000.000 | DP = Rp 84.000.000"}
      variables={[{name:'DTI (Debt-to-Income Ratio)',desc:'Rasio total cicilan terhadap penghasilan. Bank Indonesia umumnya membatasi maksimal 30–40% dari penghasilan'},{name:'Max Pinjaman',desc:'Jumlah pinjaman KPR terbesar yang disetujui berdasarkan kemampuan cicilan'},{name:'Max Harga Properti',desc:'Harga properti tertinggi yang bisa diakses dengan pinjaman dan DP yang ditetapkan'},{name:'DP (Down Payment)',desc:'Uang muka yang harus disiapkan di luar pinjaman bank — minimum 10–20% dari harga properti'}]}
      history={"Aturan debt-to-income ratio (DTI) dalam perbankan Indonesia diatur oleh Bank Indonesia melalui Peraturan Bank Indonesia tentang Rasio Loan to Value (LTV). Sejak 2021, BI menetapkan batas maksimum DTI yang lebih fleksibel bergantung pada kebijakan masing-masing bank, umumnya 30–40%.\n\nPasar KPR Indonesia mulai berkembang pesat sejak program KPR subsidi FLPP (Fasilitas Likuiditas Pembiayaan Perumahan) diluncurkan pemerintah pada 2010, yang memberikan akses KPR berbunga rendah untuk masyarakat berpenghasilan rendah.\n\nBank-bank besar seperti BTN, BCA, Mandiri, dan BRI masing-masing memiliki kebijakan KPR yang sedikit berbeda. KPR subsidi FLPP dari BTN menawarkan bunga fixed 5% untuk rumah di bawah harga tertentu — salah satu yang paling kompetitif."}
      interpretation={[{range:'DTI < 30%',label:'🟢 Sangat Sehat',desc:'Cicilan sangat ringan — masih ada banyak ruang untuk kebutuhan lain'},{range:'DTI 30–35%',label:'🟢 Sehat',desc:'Batas ideal yang masih nyaman untuk kebanyakan keluarga'},{range:'DTI 35–40%',label:'🟡 Perlu Perhatian',desc:'Sudah cukup berat — pastikan ada buffer untuk keadaan darurat'},{range:'DTI > 40%',label:'🔴 Kritis',desc:'Sangat memberatkan — pertimbangkan menunggu penghasilan naik atau DP lebih besar'}]}
      interpretationTitle="Panduan Debt-to-Income Ratio"
      faqs={[{q:'Apakah DTI 35% adalah aturan pasti bank?',a:'Bukan aturan pasti — setiap bank memiliki kebijakannya sendiri. Beberapa bank lebih konservatif (30%), beberapa lebih fleksibel (40–45%) untuk nasabah dengan profil risiko baik. DTI 35% digunakan sebagai standar umum di kalangan perencana keuangan.'},{q:'Apakah penghasilan suami-istri bisa digabung?',a:'Ya, hampir semua bank menerima joint income untuk pengajuan KPR bersama suami-istri. Ini secara signifikan meningkatkan kemampuan KPR. Pastikan keduanya hadir saat pengajuan dan siapkan dokumen penghasilan masing-masing.'},{q:'Bagaimana jika penghasilan tidak tetap (freelancer, pengusaha)?',a:'Bank umumnya membutuhkan bukti penghasilan rata-rata 2 tahun terakhir melalui laporan keuangan atau rekening koran. Sebagian besar bank lebih ketat untuk penghasilan tidak tetap — DTI yang ditetapkan bank bisa lebih rendah.'},{q:'Apakah bunga KPR bisa berubah setelah beberapa tahun?',a:'Ya. Kebanyakan KPR Indonesia menggunakan bunga fixed 1–5 tahun pertama, kemudian floating mengikuti suku bunga acuan BI. Pastikan kamu menghitung skenario jika bunga naik 2–3% saat simulasi kemampuan cicilan.'}]}
      related={[{name:'Loan True Cost Analyzer',href:'/kredit-properti/loan-true-cost-analyzer',desc:'Hitung total biaya KPR termasuk total bunga yang harus dibayar'},{name:'Buy vs Rent Analyzer',href:'/kredit-properti/buy-vs-rent-analyzer',desc:'Bandingkan apakah lebih menguntungkan beli atau sewa properti'},{name:'Refinancing Decision Tool',href:'/kredit-properti/refinancing-decision-tool',desc:'Analisis apakah refinancing KPR akan menghemat biaya'},{name:'Net Worth Tracker',href:'/personal-finance/net-worth-tracker',desc:'Pantau dampak KPR terhadap net worth dan debt ratio kamu'}]}
      references={['Bank Indonesia. <em>Peraturan Bank Indonesia tentang LTV.</em> <a href="https://bi.go.id" target="_blank" rel="noopener noreferrer" class="text-finc-green hover:underline">bi.go.id</a>','OJK. <em>Panduan KPR untuk Masyarakat.</em> <a href="https://ojk.go.id" target="_blank" rel="noopener noreferrer" class="text-finc-green hover:underline">ojk.go.id</a>','BTN. <em>Informasi KPR Subsidi FLPP.</em> <a href="https://btn.co.id" target="_blank" rel="noopener noreferrer" class="text-finc-green hover:underline">btn.co.id</a>']}
    ><KPRAffordabilityChecker /></KreditToolPage>
  </main><Footer /></>)
}
