import type { Metadata } from 'next'
import Link from 'next/link'
import { ChevronRight } from 'lucide-react'
import Header from '@/components/layout/Header'
import Footer from '@/components/layout/Footer'
import PersonalFinanceToolPage from '@/components/layout/PersonalFinanceToolPage'
import NetWorthTracker from '@/components/tools/personal-finance/NetWorthTracker'
export const metadata: Metadata = { title: 'Net Worth Tracker — Kalkulasi Kekayaan Bersih | FincTools', description: 'Kalkulasi kekayaan bersih dari total aset dikurangi total liabilitas beserta analisis debt-to-asset ratio.' }
export default function Page() {
  return (<><Header /><main className="mx-auto max-w-4xl px-4 py-8">
    <nav className="flex items-center gap-1 text-xs text-[--text-secondary] mb-6"><Link href="/" className="hover:text-finc-green">Home</Link><ChevronRight size={12}/><Link href="/personal-finance" className="hover:text-finc-green">Personal Finance</Link><ChevronRight size={12}/><span className="text-[--text-primary] font-medium">Net Worth Tracker</span></nav>
    <PersonalFinanceToolPage name="Net Worth Tracker" subcategory="Kesehatan Finansial"
      description="Net Worth Tracker menghitung kekayaan bersih kamu — total aset dikurangi total liabilitas — dan menganalisis debt-to-asset ratio sebagai indikator kesehatan finansial keseluruhan."
      steps={[{title:'Isi Semua Aset',desc:'Masukkan nilai semua yang kamu miliki: kas, tabungan, reksa dana, saham, properti, kendaraan, dan aset lainnya berdasarkan nilai pasar saat ini.'},{title:'Isi Semua Liabilitas',desc:'Masukkan sisa saldo semua utang: KPR, kredit kendaraan, kartu kredit, dan pinjaman lainnya.'},{title:'Baca Net Worth',desc:'Net Worth = Total Aset - Total Liabilitas. Angka positif berarti kamu punya lebih banyak aset dari utang.'},{title:'Evaluasi Debt Ratio',desc:'Debt-to-Asset Ratio menunjukkan berapa persen asetmu yang dibiayai utang. Di bawah 30% dianggap sehat.'}]}
      formula={"Net Worth = Total Aset - Total Liabilitas\nDebt-to-Asset Ratio = (Total Liabilitas / Total Aset) × 100%\n\nStatus:\n< 30% → Sehat\n30–50% → Perlu Perhatian\n> 50% → Kritis"}
      formulaExample={"Aset: Kas Rp 50jt + Investasi Rp 100jt + Properti Rp 500jt = Rp 650jt\nLiabilitas: KPR Rp 400jt + Kartu Kredit Rp 5jt = Rp 405jt\nNet Worth = Rp 650jt - Rp 405jt = Rp 245jt\nDebt Ratio = 405/650 = 62.3% → Kritis, perlu dilunasi"}
      variables={[{name:'Total Aset',desc:'Nilai pasar semua yang dimiliki — aset likuid, investasi, dan aset fisik'},{name:'Total Liabilitas',desc:'Saldo semua utang yang masih harus dibayar'},{name:'Net Worth',desc:'Kekayaan bersih = aset - liabilitas — ukuran sebenarnya dari kekayaanmu'},{name:'Debt Ratio',desc:'Persentase aset yang dibiayai utang — semakin rendah semakin sehat'}]}
      history={"Konsep net worth sebagai ukuran kekayaan seseorang berasal dari akuntansi korporasi yang kemudian diadaptasi untuk keuangan pribadi. Dalam laporan keuangan perusahaan, net worth dikenal sebagai stockholders equity atau book value.\n\nThomas Stanley dan William Danko dalam buku The Millionaire Next Door (1996) menemukan bahwa banyak jutawan Amerika terlihat sederhana dari luar — karena kekayaan sejati diukur dari net worth, bukan gaya hidup. Temuan mereka: jutawan rata-rata memiliki net worth minimal 10x pengeluaran tahunan.\n\nDi Indonesia, budaya 'penampilan' sering membuat orang mengutamakan aset terlihat (properti, kendaraan mewah) yang dibeli dengan utang besar — akibatnya net worth rendah meski terlihat kaya."}
      faqs={[{q:'Apa yang dianggap net worth yang baik?',a:'Tidak ada angka universal. Thomas Stanley menyarankan Net Worth ideal = (Usia × Penghasilan Tahunan) / 10. Misalnya usia 35, penghasilan Rp 300jt/tahun → Net Worth ideal Rp 1.05 miliar. Namun yang terpenting adalah tren — net worth harus tumbuh setiap tahun.'},{q:'Apakah properti yang sedang dikreditkan masuk aset?',a:'Ya — properti masuk sebagai aset berdasarkan nilai pasar saat ini, dan KPR masuk sebagai liabilitas berdasarkan sisa saldo utang. Selisihnya (equity) adalah bagian properti yang benar-benar sudah menjadi milikmu.'},{q:'Seberapa sering perlu menghitung net worth?',a:'Idealnya setiap 3–6 bulan atau minimal setahun sekali. Ini membantu melacak kemajuan finansial dari waktu ke waktu dan mendeteksi jika ada yang bergerak ke arah yang salah.'},{q:'Apakah nilai kendaraan dimasukkan sebagai aset?',a:'Ya, namun perhatikan bahwa nilai kendaraan terus menyusut (depresiasi) setiap tahun. Gunakan nilai pasar saat ini, bukan harga beli. Situs seperti OLX atau dealer bekas bisa memberikan gambaran harga pasar kendaraanmu.'}]}
      related={[{name:'Debt Destroyer',href:'/personal-finance/debt-destroyer',desc:'Strategi melunasi liabilitas untuk meningkatkan net worth'},{name:'Wealth Freedom Planner',href:'/personal-finance/wealth-freedom-planner',desc:'Hitung berapa net worth yang dibutuhkan untuk FIRE'},{name:'DCA Simulator',href:'/investasi/dca-simulator',desc:'Simulasikan pertumbuhan aset investasi untuk meningkatkan net worth'},{name:'KPR Affordability Checker',href:'/kredit-properti/kpr-affordability-checker',desc:'Pastikan KPR baru tidak membebani debt ratio secara berlebihan'}]}
      references={['Stanley, T. & Danko, W. (1996). <em>The Millionaire Next Door.</em> Longstreet Press.','Bach, D. (2004). <em>The Automatic Millionaire.</em> Broadway Books.','OJK. <em>Panduan Perencanaan Keuangan.</em> <a href="https://ojk.go.id" target="_blank" rel="noopener noreferrer" class="text-finc-green hover:underline">ojk.go.id</a>']}
    ><NetWorthTracker /></PersonalFinanceToolPage>
  </main><Footer /></>)
}
