import type { Metadata } from 'next'
import Link from 'next/link'
import { ChevronRight } from 'lucide-react'
import Header from '@/components/layout/Header'
import Footer from '@/components/layout/Footer'
import PersonalFinanceToolPage from '@/components/layout/PersonalFinanceToolPage'
import GoalAchieverPlanner from '@/components/tools/personal-finance/GoalAchieverPlanner'
export const metadata: Metadata = { title: 'Goal Achiever Planner — Hitung Tabungan untuk Tujuan Finansial | FincTools', description: 'Hitung berapa yang harus ditabung per bulan untuk mencapai tujuan finansial tertentu dalam waktu yang ditetapkan.' }
export default function Page() {
  return (<><Header /><main className="mx-auto max-w-4xl px-4 py-8">
    <nav className="flex items-center gap-1 text-xs text-[--text-secondary] mb-6"><Link href="/" className="hover:text-finc-green">Home</Link><ChevronRight size={12}/><Link href="/personal-finance" className="hover:text-finc-green">Personal Finance</Link><ChevronRight size={12}/><span className="text-[--text-primary] font-medium">Goal Achiever Planner</span></nav>
    <PersonalFinanceToolPage name="Goal Achiever Planner" subcategory="Perencanaan Tujuan"
      description="Goal Achiever Planner menghitung berapa yang harus ditabung setiap bulan untuk mencapai tujuan finansial tertentu dalam waktu yang sudah ditetapkan — dengan memperhitungkan dana yang sudah ada dan return investasi."
      steps={[{title:'Tentukan Target Jumlah',desc:'Berapa yang kamu butuhkan? Contoh: DP rumah Rp 200 juta, biaya nikah Rp 100 juta, dana pendidikan anak Rp 500 juta.'},{title:'Isi Dana yang Sudah Ada',desc:'Jika sudah punya tabungan awal untuk tujuan ini, masukkan nominalnya — ini akan mengurangi beban tabungan bulanan.'},{title:'Set Waktu Pencapaian',desc:'Berapa bulan dari sekarang kamu ingin mencapai target. 24 bulan = 2 tahun, 60 bulan = 5 tahun.'},{title:'Set Return/Bunga',desc:'Jika ditabung di reksa dana pasar uang, gunakan 5–6%. Reksa dana campuran 8–10%. Tabungan biasa 1–2%.'},{title:'Baca Hasilnya',desc:'Tabungan per bulan yang dibutuhkan, dan berapa persen target sudah tercover dari dana awal.'}]}
      formula={"PMT = (Target - PV×(1+r)^n) / ((1+r)^n - 1) × r\nr = return per bulan (return tahunan / 12)\nn = jumlah bulan target\nPV = dana awal yang sudah ada\nPMT = tabungan per bulan yang dibutuhkan"}
      formulaExample={"Target DP Rumah Rp 200jt | Ada Rp 20jt | 36 bulan | return 6%/tahun\nr = 6%/12 = 0.5%/bln\nPV tumbuh = 20jt × (1.005)^36 = Rp 23.9jt\nKekurangan = 200jt - 23.9jt = Rp 176.1jt\nPMT = 176.1jt × 0.5% / ((1.005)^36 - 1) ≈ Rp 4.600.000/bln"}
      variables={[{name:'Target',desc:'Jumlah uang yang dibutuhkan untuk mencapai tujuan finansial'},{name:'PV',desc:'Dana awal yang sudah tersedia dan akan diinvestasikan menuju target'},{name:'n',desc:'Jumlah bulan waktu yang tersedia untuk mencapai target'},{name:'r',desc:'Return investasi per bulan'},{name:'PMT',desc:'Jumlah tabungan per bulan yang dibutuhkan untuk mencapai target'}]}
      history={"Goal-based financial planning atau perencanaan keuangan berbasis tujuan adalah pendekatan modern yang menggantikan budgeting tradisional yang berfokus pada pembatasan pengeluaran. Pendekatan ini dipopulerkan oleh Mitch Anthony dalam buku The New Retirementality (2008) dan dikembangkan lebih lanjut oleh industri manajemen aset global.\n\nLembaga keuangan besar seperti Vanguard dan Fidelity mengadopsi goal-based investing sebagai framework utama dalam manajemen portofolio. Riset menunjukkan bahwa investor yang memiliki tujuan spesifik dengan timeline yang jelas lebih konsisten dalam berinvestasi dan lebih kecil kemungkinannya menarik dana saat pasar turun.\n\nDi Indonesia, OJK mendorong literasi keuangan berbasis tujuan melalui kampanye 'Yuk Menabung' dan berbagai program edukasi — mengingat tingkat tabungan Indonesia masih relatif rendah dibanding negara ASEAN lainnya."}
      faqs={[{q:'Bagaimana jika target tabungan per bulan melebihi kemampuan?',a:'Ada tiga cara menyesuaikan: perpanjang waktu pencapaian (target bulan ditambah), turunkan target jumlah (evaluasi apakah target bisa dikurangi), atau cari instrumen investasi dengan return lebih tinggi. Prioritaskan yang paling realistis.'},{q:'Tujuan apa saja yang cocok menggunakan tool ini?',a:'Down payment rumah, biaya pernikahan, dana pendidikan anak, modal usaha, biaya liburan impian, pembelian kendaraan, renovasi rumah, atau tujuan finansial apapun yang memiliki angka dan timeline yang spesifik.'},{q:'Apakah dana untuk beberapa tujuan perlu dipisah?',a:'Sangat direkomendasikan. Pisahkan tabungan untuk setiap tujuan ke rekening atau instrumen berbeda — ini mencegah dana saling "meminjam" dan memudahkan tracking kemajuan masing-masing tujuan.'},{q:'Bagaimana jika ada dana tak terduga yang bisa ditambahkan?',a:'Manfaatkan bonus, THR, atau rejeki tak terduga untuk menambah dana tujuan. Ini akan mempercepat pencapaian atau mengurangi beban tabungan bulanan yang dibutuhkan di bulan-bulan berikutnya.'}]}
      related={[{name:'Savings Growth Simulator',href:'/personal-finance/savings-growth-simulator',desc:'Proyeksikan pertumbuhan tabungan menuju tujuan finansialmu'},{name:'Emergency Shield Builder',href:'/personal-finance/emergency-shield-builder',desc:'Bangun dana darurat sebelum mengejar tujuan finansial lainnya'},{name:'DCA Simulator',href:'/investasi/dca-simulator',desc:'Investasikan tabungan bulanan dengan strategi DCA'},{name:'Budget Architect',href:'/personal-finance/budget-architect',desc:'Susun anggaran untuk mengidentifikasi dari mana tabungan tujuan akan diambil'}]}
      references={['Anthony, M. (2008). <em>The New Retirementality.</em> Wiley.','Vanguard Research. (2022). <em>Goal-Based Investing.</em> Vanguard Group.','OJK. <em>Panduan Perencanaan Keuangan.</em> <a href="https://ojk.go.id" target="_blank" rel="noopener noreferrer" class="text-finc-green hover:underline">ojk.go.id</a>']}
    ><GoalAchieverPlanner /></PersonalFinanceToolPage>
  </main><Footer /></>)
}
