import type { Metadata } from 'next'
import Link from 'next/link'
import { ChevronRight } from 'lucide-react'
import Header from '@/components/layout/Header'
import Footer from '@/components/layout/Footer'
import SahamToolPage from '@/components/layout/SahamToolPage'
import EntryPriceOptimizer from '@/components/tools/saham/EntryPriceOptimizer'
export const metadata: Metadata = { title: 'Entry Price Optimizer — Lot Optimal Berdasarkan Risiko | FincTools', description: 'Tentukan jumlah lot saham yang optimal berdasarkan modal, risiko per trade, stop loss, dan target profit.' }
export default function Page() {
  return (<><Header /><main className="mx-auto max-w-4xl px-4 py-8">
    <nav className="flex items-center gap-1 text-xs text-[--text-secondary] mb-6"><Link href="/" className="hover:text-finc-green">Home</Link><ChevronRight size={12}/><Link href="/saham" className="hover:text-finc-green">Saham</Link><ChevronRight size={12}/><span className="text-[--text-primary] font-medium">Entry Price Optimizer</span></nav>
    <SahamToolPage name="Entry Price Optimizer" description="Entry Price Optimizer membantu kamu menentukan jumlah lot saham yang optimal berdasarkan modal, risiko per trade, level stop loss, dan target profit — sehingga setiap entry terencana dengan baik secara matematis."
      steps={[{title:'Isi Harga Entry',desc:'Masukkan harga per lembar yang kamu rencanakan sebagai harga beli.'},{title:'Set Persentase Stop Loss',desc:'Berapa persen di bawah entry harga kamu akan cut loss. Contoh: 5% artinya stop loss di 95% dari harga entry.'},{title:'Set Target Profit',desc:'Target kenaikan harga dalam persen. Contoh: 15% artinya take profit di 115% dari harga entry.'},{title:'Isi Modal dan Risiko',desc:'Masukkan total modal investasi dan persentase modal yang siap dirisikoan per trade.'},{title:'Baca Hasilnya',desc:'Lot optimal, harga stop loss dan take profit, R/R ratio, dan modal yang berisiko ditampilkan lengkap.'}]}
      formula={"R/R Ratio = Target Profit % / Stop Loss %\nModal Berisiko = Modal × % Risiko\nLot Optimal = ⌊Modal Berisiko / (Harga Entry × SL% × 100)⌋\nHarga SL = Harga Entry × (1 - SL%)\nHarga TP = Harga Entry × (1 + TP%)"}
      formulaExample={"Modal Rp 100.000.000 | Risiko 2% | Entry Rp 5.000 | SL 5% | TP 15%\nModal Berisiko = Rp 2.000.000\nLot Optimal = ⌊2.000.000 / (5.000 × 5% × 100)⌋ = 8 lot\nR/R = 15% / 5% = 1:3 ✅"}
      variables={[{name:'Harga Entry',desc:'Harga per lembar saat rencana membeli saham'},{name:'Stop Loss %',desc:'Persentase penurunan dari entry sebagai batas cut loss'},{name:'Target Profit %',desc:'Persentase kenaikan dari entry sebagai target take profit'},{name:'Modal Berisiko',desc:'Modal × % Risiko = jumlah maksimum yang siap hilang dalam satu trade'},{name:'Lot Optimal',desc:'Jumlah lot terbesar yang aman berdasarkan modal berisiko dan stop loss'}]}
      history={"Konsep position sizing berbasis persentase risiko dikembangkan oleh Van K. Tharp melalui bukunya Trade Your Way to Financial Freedom (1998). Tharp membuktikan secara matematis bahwa lot yang konsisten berdasarkan persen risiko — bukan feeling — adalah fondasi trading yang sustainable.\n\nPada saham Indonesia, perhitungan lot memperhitungkan satuan 1 lot = 100 lembar. Investor ritel sering mengabaikan aspek ini dan membeli berdasarkan 'rasa' — akibatnya exposure terhadap satu saham bisa terlalu besar atau terlalu kecil.\n\nPrinsip ini sama dengan Risk Manager untuk forex — namun diadaptasi untuk pasar saham Indonesia dengan satuan lot dan harga per lembar."}
      interpretation={[{range:'R/R < 1',label:'🔴 Buruk',desc:'Target lebih kecil dari risiko — hindari'},{range:'R/R 1–2',label:'🟡 Minimal',desc:'Butuh win rate > 50% untuk profitable'},{range:'R/R ≥ 2',label:'🟢 Baik',desc:'Standar minimum yang direkomendasikan'},{range:'R/R ≥ 3',label:'🟢 Sangat Baik',desc:'Potensi reward jauh melebihi risiko'}]}
      interpretationTitle="Panduan Risk/Reward Ratio Saham"
      faqs={[{q:'Mengapa lot optimal berbeda dari yang saya inginkan?',a:'Tool ini menghitung lot berdasarkan risiko modal yang ditetapkan — bukan berdasarkan keinginan atau feeling. Jika lot hasil kalkulasi terlalu kecil, kemungkinan stop loss terlalu jauh atau modal berisiko terlalu sedikit.'},{q:'Apa itu R/R ratio dan kenapa penting?',a:'Risk/Reward ratio adalah perbandingan antara potensi keuntungan dan potensi kerugian. R/R 1:2 artinya untuk setiap Rp 1 yang dirisikoan, potensi untungnya Rp 2. Dengan R/R minimal 1:2, kamu bisa profitable meski hanya 40% trade yang untung.'},{q:'Bagaimana cara menentukan stop loss yang tepat?',a:'Idealnya stop loss ditempatkan di level teknikal yang valid — di bawah support, di bawah low terbaru, atau di luar area konsolidasi. Jangan menempatkan stop loss secara acak berdasarkan persen semata.'},{q:'Apakah ini cocok untuk saham blue chip dan saham kecil?',a:'Ya, formula berlaku untuk saham apapun. Namun untuk saham dengan likuiditas rendah (volume kecil), lot optimal yang dihasilkan mungkin sulit dieksekusi di harga yang diinginkan karena spread yang lebar.'}]}
      related={[{name:'Averaging Strategy Builder',href:'/saham/averaging-strategy-builder',desc:'Kalkulasi harga rata-rata setelah menambah posisi'},{name:'Break-even Analyzer',href:'/saham/break-even-analyzer',desc:'Hitung harga jual minimum untuk balik modal termasuk fee'},{name:'Risk Manager',href:'/trading/risk-manager',desc:'Versi trading untuk forex dan instrumen lain'},{name:'Trade Analyzer',href:'/trading/trade-analyzer',desc:'Analisis Risk/Reward ratio secara detail'}]}
      references={['Tharp, V.K. (1998). <em>Trade Your Way to Financial Freedom.</em> McGraw-Hill.','Minervini, M. (2013). <em>Trade Like a Stock Market Wizard.</em> McGraw-Hill.','IDX. <em>Panduan Investasi Saham.</em> <a href="https://idx.co.id" target="_blank" rel="noopener noreferrer" class="text-finc-green hover:underline">idx.co.id</a>']}
    ><EntryPriceOptimizer /></SahamToolPage>
  </main><Footer /></>)
}
