import type { Metadata } from 'next'
import Link from 'next/link'
import { ChevronRight } from 'lucide-react'
import Header from '@/components/layout/Header'
import Footer from '@/components/layout/Footer'
import PersonalFinanceToolPage from '@/components/layout/PersonalFinanceToolPage'
import WealthFreedomPlanner from '@/components/tools/personal-finance/WealthFreedomPlanner'
export const metadata: Metadata = { title: 'Wealth Freedom Planner — Hitung Angka FIRE | FincTools', description: 'Hitung angka FIRE (Financial Independence, Retire Early) dan estimasi kapan kamu bisa pensiun dini berdasarkan pengeluaran dan return investasi.' }
export default function Page() {
  return (<><Header /><main className="mx-auto max-w-4xl px-4 py-8">
    <nav className="flex items-center gap-1 text-xs text-[--text-secondary] mb-6"><Link href="/" className="hover:text-finc-green">Home</Link><ChevronRight size={12}/><Link href="/personal-finance" className="hover:text-finc-green">Personal Finance</Link><ChevronRight size={12}/><span className="text-[--text-primary] font-medium">Wealth Freedom Planner</span></nav>
    <PersonalFinanceToolPage name="Wealth Freedom Planner" subcategory="FIRE Planning"
      description="Wealth Freedom Planner menghitung FIRE Number — jumlah aset yang kamu butuhkan agar bisa berhenti bekerja dan hidup dari hasil investasi selamanya — berdasarkan pengeluaran bulanan dan estimasi return investasi."
      steps={[{title:'Isi Pengeluaran Bulanan',desc:'Masukkan total pengeluaran bulanan yang kamu proyeksikan saat sudah tidak bekerja — termasuk kebutuhan, keinginan, dan buffer tak terduga.'},{title:'Isi Tabungan & Investasi Saat Ini',desc:'Total aset investasi yang sudah kamu miliki sekarang — reksa dana, saham, deposito, dan aset likuid lainnya.'},{title:'Isi Investasi Bulanan',desc:'Berapa yang rutin kamu investasikan setiap bulan saat ini.'},{title:'Set Estimasi Return & Inflasi',desc:'Gunakan estimasi konservatif. Return reksa dana saham historis Indonesia 12–15%/tahun. Inflasi Indonesia historis 3–5%.'},{title:'Baca Hasilnya',desc:'FIRE Number dan estimasi waktu untuk mencapainya berdasarkan asumsi yang kamu masukkan.'}]}
      formula={"FIRE Number = Pengeluaran Tahunan / Safe Withdrawal Rate (4%)\nPengeluaran Tahunan = Pengeluaran Bulanan × 12\nReturn Riil = Return Tahunan - Inflasi Tahunan\nWaktu FIRE = Hitung iterasi sampai portofolio = FIRE Number"}
      formulaExample={"Pengeluaran Rp 10.000.000/bulan\nPengeluaran Tahunan = Rp 120.000.000\nFIRE Number = 120.000.000 / 4% = Rp 3.000.000.000\nDengan Rp 100jt awal + Rp 5jt/bulan @ 12% return ≈ 25 tahun"}
      variables={[{name:'FIRE Number',desc:'Jumlah total aset yang dibutuhkan agar investasi menghasilkan cukup untuk biaya hidup selamanya'},{name:'Safe Withdrawal Rate',desc:'4% Rule — persentase aman yang bisa ditarik dari portofolio setiap tahun tanpa menghabiskan pokok'},{name:'Return Riil',desc:'Return investasi setelah dikurangi inflasi — return yang benar-benar meningkatkan daya beli'}]}
      history={"Konsep FIRE (Financial Independence, Retire Early) dipopulerkan oleh Vicki Robin dan Joe Dominguez dalam buku Your Money or Your Life (1992). Namun dasar matematisnya — 4% Safe Withdrawal Rate — berasal dari penelitian William Bengen (1994) yang dipublikasikan dalam Journal of Financial Planning.\n\nBengen menganalisis data historis pasar saham AS selama 50+ tahun dan menemukan bahwa menarik 4% per tahun dari portofolio yang terdiversifikasi tidak akan pernah menghabiskan pokok dalam 30 tahun — bahkan melewati krisis 1929 dan 1973.\n\nDi Indonesia, gerakan FIRE mulai populer setelah 2015 seiring meningkatnya literasi investasi reksa dana dan kemudahan akses melalui aplikasi fintech. Namun FIRE Number di Indonesia perlu disesuaikan dengan inflasi lokal yang historis lebih tinggi dari negara maju."}
      faqs={[{q:'Apakah 4% Safe Withdrawal Rate berlaku untuk Indonesia?',a:'4% Rule berasal dari riset pasar saham AS. Untuk Indonesia, beberapa perencana keuangan merekomendasikan menggunakan 3–3.5% sebagai SWR yang lebih konservatif mengingat volatilitas pasar yang lebih tinggi dan inflasi yang cenderung lebih besar.'},{q:'Apakah FIRE berarti tidak bekerja sama sekali?',a:'Tidak harus. Banyak pelaku FIRE tetap bekerja atau berbisnis — namun karena pilihan, bukan karena terpaksa. Kondisi ini sering disebut "Coast FIRE" atau "Barista FIRE" di mana penghasilan kerja hanya untuk biaya hidup sementara investasi terus bertumbuh.'},{q:'Bagaimana jika return investasi berbeda dari estimasi?',a:'FIRE Number adalah estimasi berbasis asumsi — bukan jaminan. Untuk keamanan, tambahkan buffer 20–30% dari FIRE Number yang dihitung, gunakan asumsi return yang konservatif, dan diversifikasi aset ke beberapa instrumen.'},{q:'Apakah FIRE realistis untuk gaji rata-rata Indonesia?',a:'Sangat bergantung pada rasio tabungan. Jika bisa menabung 30–50% dari penghasilan dan berinvestasi dengan disiplin sejak awal karir, FIRE di usia 45–55 sangat realistis. Yang terpenting adalah memulai lebih awal.'}]}
      related={[{name:'Savings Growth Simulator',href:'/personal-finance/savings-growth-simulator',desc:'Proyeksikan pertumbuhan tabungan dan investasi secara detail'},{name:'Goal Achiever Planner',href:'/personal-finance/goal-achiever-planner',desc:'Hitung berapa yang perlu ditabung untuk mencapai target FIRE Number'},{name:'DCA Simulator',href:'/investasi/dca-simulator',desc:'Simulasi investasi rutin menuju FIRE Number'},{name:'Inflation Guard',href:'/personal-finance/inflation-guard',desc:'Pahami dampak inflasi terhadap FIRE Number di masa depan'}]}
      references={['Bengen, W.P. (1994). Determining Withdrawal Rates Using Historical Data. <em>Journal of Financial Planning.</em>','Robin, V. & Dominguez, J. (1992). <em>Your Money or Your Life.</em> Viking.','OJK. <em>Panduan Perencanaan Keuangan.</em> <a href="https://ojk.go.id" target="_blank" rel="noopener noreferrer" class="text-finc-green hover:underline">ojk.go.id</a>']}
    ><WealthFreedomPlanner /></PersonalFinanceToolPage>
  </main><Footer /></>)
}
