import type { Metadata } from 'next'
import Link from 'next/link'
import { ChevronRight } from 'lucide-react'
import Header from '@/components/layout/Header'
import Footer from '@/components/layout/Footer'
import KriptoToolPage from '@/components/layout/KriptoToolPage'
import CryptoDCASimulator from '@/components/tools/kripto/CryptoDCASimulator'
export const metadata: Metadata = { title: 'Crypto DCA Simulator — Simulasi DCA Kripto | FincTools', description: 'Simulasi Dollar Cost Averaging untuk aset kripto. Hitung koin yang terkumpul dan nilai portofolio di target harga.' }
export default function Page() {
  return (<><Header /><main className="mx-auto max-w-4xl px-4 py-8">
    <nav className="flex items-center gap-1 text-xs text-[--text-secondary] mb-6"><Link href="/" className="hover:text-finc-green">Home</Link><ChevronRight size={12}/><Link href="/kripto" className="hover:text-finc-green">Kripto</Link><ChevronRight size={12}/><span className="text-[--text-primary] font-medium">Crypto DCA Simulator</span></nav>
    <KriptoToolPage name="Crypto DCA Simulator" subcategory="Strategi Investasi"
      description="Crypto DCA Simulator mensimulasikan strategi Dollar Cost Averaging untuk aset kripto — menghitung total koin yang terkumpul dan proyeksi nilai portofolio jika harga mencapai target yang kamu tentukan."
      steps={[{title:'Isi Investasi per Bulan',desc:'Berapa yang akan kamu investasikan setiap bulan secara konsisten — inilah esensi DCA.'},{title:'Set Durasi',desc:'Berapa bulan kamu berencana DCA. Kripto membutuhkan horizon minimal 2–3 tahun untuk mengurangi risiko volatilitas.'},{title:'Isi Harga Aset Saat Ini',desc:'Masukkan harga aset kripto yang ingin kamu DCA dalam Rupiah per unit.'},{title:'Set Target Harga',desc:'Berapa harga target yang kamu proyeksikan untuk aset ini di masa depan.'},{title:'Baca Hasilnya',desc:'Total koin terkumpul, nilai sekarang, nilai di target harga, dan return ditampilkan.'}]}
      formula={"Koin per Bulan = Investasi per Bulan / Harga Saat Ini\nTotal Koin = Koin per Bulan × Jumlah Bulan\nNilai Sekarang = Total Koin × Harga Saat Ini\nNilai Target = Total Koin × Target Harga\nReturn = (Nilai Target - Total Investasi) / Total Investasi × 100%"}
      formulaExample={"DCA Rp 500.000/bln selama 24 bulan | Harga BTC Rp 900jt | Target Rp 1.5M\nKoin/bln = 500.000 / 900.000.000 = 0.000556 BTC\nTotal Koin = 0.000556 × 24 = 0.01333 BTC\nNilai Target = 0.01333 × 1.500.000.000 = Rp 19.996.000\nReturn = (19.996.000 - 12.000.000) / 12.000.000 = +66.6%"}
      variables={[{name:'Koin per Bulan',desc:'Jumlah koin yang dibeli setiap bulan berdasarkan investasi dan harga saat ini'},{name:'Total Koin',desc:'Akumulasi total koin setelah semua periode DCA'},{name:'Target Harga',desc:'Proyeksi harga aset di masa depan yang menjadi basis perhitungan nilai portofolio'}]}
      history={"Dollar Cost Averaging pertama kali diformulasikan oleh Benjamin Graham dan kemudian diadaptasi ke pasar kripto seiring popularitas Bitcoin. Strategi ini menjadi sangat relevan untuk aset dengan volatilitas tinggi seperti kripto.\n\nPenelitian dari University of Wisconsin (2020) menunjukkan bahwa DCA selama 4 tahun pada Bitcoin menghasilkan return positif di 93% dari semua 4-tahun periode yang pernah ada — bahkan jika kamu mulai DCA tepat di puncak harga tertinggi.\n\nDi Indonesia, platform kripto seperti Pintu, Indodax, dan Tokocrypto menyediakan fitur DCA otomatis yang memudahkan eksekusi strategi ini tanpa harus ingat membeli setiap bulan."}
      faqs={[{q:'Apakah DCA cocok untuk semua aset kripto?',a:'DCA paling cocok untuk aset kripto dengan fundamental kuat dan likuiditas tinggi seperti Bitcoin dan Ethereum. Untuk altcoin kecil dengan risiko proyek gagal, DCA berbahaya karena bisa terus berinvestasi di aset yang nilainya menuju nol.'},{q:'Berapa lama minimal DCA kripto untuk hasil optimal?',a:'Minimal 2–3 tahun untuk mengurangi risiko masuk di puncak siklus. Sejarah Bitcoin menunjukkan siklus 4 tahunan (halving cycle). DCA selama minimal 1 siklus penuh memberikan eksposur ke berbagai kondisi pasar.'},{q:'Apa perbedaan DCA kripto dengan DCA reksa dana?',a:'Konsep dasarnya sama — beli rutin tanpa mempertimbangkan harga. Namun kripto jauh lebih volatile, tidak ada regulasi yang melindungi investor, dan risikonya jauh lebih tinggi. Pertimbangkan alokasi kripto maksimal 5–10% dari total portofolio investasi.'},{q:'Apakah perlu beli pas harga turun daripada DCA rutin?',a:'Penelitian menunjukkan DCA rutin (tanpa mempertimbangkan harga) menghasilkan return yang mendekati strategi "beli saat turun" dalam jangka panjang — namun jauh lebih mudah dilaksanakan karena tidak butuh analisis timing.'}]}
      related={[{name:'Crypto Risk Manager',href:'/kripto/crypto-risk-manager',desc:'Hitung position sizing untuk trading kripto secara aman'},{name:'Staking Reward Projector',href:'/kripto/staking-reward-projector',desc:'Projeksi reward dari staking koin yang sudah terkumpul'},{name:'DCA Simulator',href:'/investasi/dca-simulator',desc:'Versi DCA untuk reksa dana dan saham (lebih konservatif)'},{name:'Liquidation Price Analyzer',href:'/kripto/liquidation-price-analyzer',desc:'Cek risiko likuidasi jika trading futures kripto'}]}
      references={['Nakamoto, S. (2008). <em>Bitcoin: A Peer-to-Peer Electronic Cash System.</em>','Biais, B. et al. (2019). The Blockchain Folk Theorem. <em>Review of Financial Studies.</em>','OJK. <em>Kebijakan Aset Kripto Indonesia.</em> <a href="https://ojk.go.id" target="_blank" rel="noopener noreferrer" class="text-finc-green hover:underline">ojk.go.id</a>']}
    ><CryptoDCASimulator /></KriptoToolPage>
  </main><Footer /></>)
}
