import type { Metadata } from 'next'
import Link from 'next/link'
import { ChevronRight } from 'lucide-react'
import Header from '@/components/layout/Header'
import Footer from '@/components/layout/Footer'
import SahamToolPage from '@/components/layout/SahamToolPage'
import BreakEvenAnalyzer from '@/components/tools/saham/BreakEvenAnalyzer'
export const metadata: Metadata = { title: 'Break-even Analyzer — Harga Jual Minimum Saham | FincTools', description: 'Hitung harga jual minimum saham untuk balik modal setelah memperhitungkan biaya fee beli dan fee jual broker.' }
export default function Page() {
  return (<><Header /><main className="mx-auto max-w-4xl px-4 py-8">
    <nav className="flex items-center gap-1 text-xs text-[--text-secondary] mb-6"><Link href="/" className="hover:text-finc-green">Home</Link><ChevronRight size={12}/><Link href="/saham" className="hover:text-finc-green">Saham</Link><ChevronRight size={12}/><span className="text-[--text-primary] font-medium">Break-even Analyzer</span></nav>
    <SahamToolPage name="Break-even Analyzer" description="Break-even Analyzer menghitung harga jual minimum saham agar kamu tidak merugi setelah memperhitungkan biaya fee beli dan fee jual broker. Harga ini selalu lebih tinggi dari harga beli karena ada fee yang harus ditanggung."
      steps={[{title:'Isi Harga Beli',desc:'Masukkan harga per lembar saham saat kamu membeli.'},{title:'Isi Jumlah Lot',desc:'Berapa lot yang kamu beli.'},{title:'Set Fee Beli',desc:'Fee beli broker dalam persen. Umumnya 0.10–0.19% untuk online trading Indonesia.'},{title:'Set Fee Jual',desc:'Fee jual termasuk pajak PPh 0.1%. Umumnya 0.20–0.29% untuk online trading Indonesia.'},{title:'Baca Hasilnya',desc:'Harga jual minimum dan selisih dari harga beli ditampilkan — ini harga yang harus dilampaui agar kamu tidak rugi.'}]}
      formula={"Total Modal = Harga Beli × Lot × 100 × (1 + Fee Beli%)\nHarga Jual Min = Total Modal / (Lot × 100 × (1 - Fee Jual%))\nSelisih = Harga Jual Min - Harga Beli\n% Selisih = Selisih / Harga Beli × 100"}
      formulaExample={"Beli 10 lot @ Rp 5.000 | Fee Beli 0.19% | Fee Jual 0.29%\nTotal Modal = 5.000.000 × 1.0019 = Rp 5.009.500\nHarga Jual Min = 5.009.500 / (1000 × 0.9971) = Rp 5.024\nSelisih = Rp 24/lembar (+0.48%) dari harga beli"}
      variables={[{name:'Fee Beli',desc:'Biaya transaksi pembelian saham — dipotong dari total nilai beli'},{name:'Fee Jual',desc:'Biaya transaksi penjualan + pajak PPh 0.1% — dipotong dari hasil jual'},{name:'Harga Jual Min',desc:'Harga minimum yang harus dicapai agar tidak merugi setelah semua fee'},{name:'Total Fee',desc:'Jumlah seluruh biaya transaksi beli dan jual yang ditanggung investor'}]}
      history={"Di pasar saham Indonesia, setiap transaksi dikenakan biaya yang terdiri dari fee broker dan pajak pemerintah. Pajak atas transaksi penjualan saham (PPh Pasal 4 ayat 2) sebesar 0.1% dari nilai jual sudah diberlakukan sejak tahun 1995 melalui PP No. 41 Tahun 1994.\n\nFee broker bervariasi antar perusahaan sekuritas — umumnya 0.15–0.25% untuk beli dan 0.25–0.35% untuk jual (sudah termasuk pajak). Broker online modern seperti Ajaib, Stockbit, dan IPOT menawarkan fee lebih rendah untuk menarik investor ritel.\n\nBanyak investor pemula tidak menyadari bahwa mereka harus menjual di harga lebih tinggi dari harga beli untuk sekadar break-even. Break-even Analyzer menghitung angka ini secara presisi sehingga ekspektasi return realistis."}
      faqs={[{q:'Mengapa harga jual harus lebih tinggi dari harga beli?',a:'Karena ada dua biaya yang harus ditanggung: fee beli saat membeli dan fee jual saat menjual. Keduanya mengurangi nilai transaksi. Jika kamu beli dan jual di harga sama, kamu rugi sebesar total fee kedua transaksi tersebut.'},{q:'Berapa fee broker yang umum di Indonesia?',a:'Umumnya fee beli 0.15–0.19% dan fee jual 0.25–0.29% (sudah termasuk pajak 0.1%). Beberapa broker premium mengenakan lebih tinggi, sementara broker fintech online lebih rendah. Cek tarif fee di platform broker kamu.'},{q:'Apakah fee berpengaruh besar untuk saham harga rendah?',a:'Ya, sangat signifikan. Untuk saham harga Rp 50 (gocap), break-even bisa berada di Rp 50 + Rp 1 (2%) hanya untuk menutup fee. Saham harga rendah butuh kenaikan persentase lebih besar untuk profitable.'},{q:'Bisakah saya negosiasi fee dengan broker?',a:'Untuk investor dengan volume transaksi besar, beberapa broker menawarkan negosiasi fee. Namun untuk investor ritel, fee sudah terstandar. Pilih broker dengan fee paling kompetitif yang tetap menawarkan layanan andal.'}]}
      related={[{name:'Averaging Strategy Builder',href:'/saham/averaging-strategy-builder',desc:'Hitung harga rata-rata setelah menambah posisi saham'},{name:'Entry Price Optimizer',href:'/saham/entry-price-optimizer',desc:'Tentukan lot optimal berdasarkan modal dan risiko'},{name:'Trade Analyzer',href:'/trading/trade-analyzer',desc:'Analisis Risk/Reward ratio sebelum entry'},{name:'Dividend Income Projector',href:'/investasi/dividend-income-projector',desc:'Proyeksi penghasilan dividen dari portofolio saham'}]}
      references={['PP No. 41 Tahun 1994 jo PP No. 14 Tahun 1997 — Pajak Penghasilan atas Transaksi Saham.','IDX. <em>Panduan Transaksi Saham.</em> <a href="https://idx.co.id" target="_blank" rel="noopener noreferrer" class="text-finc-green hover:underline">idx.co.id</a>','OJK. <em>Panduan Pasar Modal.</em> <a href="https://ojk.go.id" target="_blank" rel="noopener noreferrer" class="text-finc-green hover:underline">ojk.go.id</a>']}
    ><BreakEvenAnalyzer /></SahamToolPage>
  </main><Footer /></>)
}
